### ISSUE TITLE
Undefined reference to `vformat_to` with `locale_ref` on clang-trunk

### ISSUE THREAD

**Issue by ShawnZhong** [fmtlib/fmt#3273]
The following [code snippet](https://godbolt.org/z/v7h7G86Pr) failed to compile on clang-trunk with fmt-trunk.
```cpp
#include <locale>
#include <fmt/format.h>

int main() {
  fmt::format(std::locale(), "");
}
```

The error message is
```
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/13.0.0/../../../../x86_64-linux-gnu/bin/ld: /tmp/example-241f30.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > fmt::v9::detail::vformat<std::locale, char>(std::locale const&, fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<std::conditional<std::is_same<fmt::v9::type_identity<char>::type, char>::value, fmt::v9::appender, std::back_insert_iterator<fmt::v9::detail::buffer<fmt::v9::type_identity<char>::type> > >::type, fmt::v9::type_identity<char>::type> >)':
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:3734: undefined reference to `void fmt::v9::detail::vformat_to<char>(fmt::v9::detail::buffer<char>&, fmt::v9::basic_string_view<char>, fmt::v9::detail::vformat_args<char>::type, fmt::v9::detail::locale_ref)'
```

The same code compiles fine on gcc-trunk and clang-15.0.0. It also works with fmt-9.1.0.
Removing the `std::locale` argument also makes it compile on clang-trunk.
I'm not sure if this is a bug in fmt or godbolt or clang-trunk, but I thought I'd report it here first.

**Comment by ShawnZhong** [comment]
Seem to be related to https://github.com/fmtlib/fmt/commit/6056e07125a2c84f5fb1b65e14bf8d851a840071. 

I start to think if it might be compiler explorer using an older version of `libfmtd.a` during linking.

**Comment by vitaut** [comment]
The symbol is present when compiling with clang trunk (https://godbolt.org/z/4Efnx7svb) so it looks like some build configuration issue rather than an {fmt} issue.

**Comment by abbradar** [comment]
I have an issue which seems to be related. I have a Nix shell (basically a Python virtualenv for everything) setup with two possible compilers: GCC 13.1 and Clang 16.0.1. Clang is configured to use the very same `libstdc++` that GCC uses. I also use Fmt from Nixpkgs which is built with GCC (but the compiler can be easily switched). My intention is to use one pre-built Fmt with both GCC and Clang projects.

Now comes the strange part: when I try to build an example using `fmt::format_to` with Clang 16 and Fmt built with GCC 13, I get this error:

```
clang++ "tests/test_hex.cpp" -MMD -MP -MF "build/tests/test_hex.d" -std=gnu++2b -Wall -Wextra -Wno-missing-field-initializers -Iinclude -march=native -Wno-c++2b-extensions -Wno-gnu-string-literal-operator-template -O0 -ggdb -fno-omit-frame-pointer   -no-pie -lCatch2Main -lCatch2 -fprofile-instr-generate -fcoverage-mapping -ffunction-sections -fdata-sections -lfmt -o "build/tests/test_hex"
/nix/store/22p5nv7fbxhm06mfkwwnibv1nsz06x4b-binutils-2.40/bin/ld: /tmp/nix-shell.HgqBKQ/test_hex-035bf4.o: in function `char* fmt::v9::vformat_to<char*, 0>(char*, fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char> >)':
/nix/store/a36h679jd8n1lvlmi16746wp5657mbzb-fmt-9.1.0-dev/include/fmt/core.h:3215: undefined reference to `void fmt::v9::detail::vformat_to<char>(fmt::v9::detail::buffer<char>&, fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<std::conditional<std::is_same<fmt::v9::type_identity<char>::type, char>::value, fmt::v9::appender, std::back_insert_iterator<fmt::v9::detail::buffer<fmt::v9::type_identity<char>::type> > >::type, fmt::v9::type_identity<char>::type> >, fmt::v9::detail::locale_ref)'
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
```

I tried, as an experiment, to build Fmt with Clang instead. Now I can compile the test with Clang, but I see the symmetrical error with GCC!

```
g++ "tests/test_hex.cpp" -MMD -MP -MF "build/tests/test_hex.d" -std=gnu++2b -Wall -Wextra -Wno-missing-field-initializers -Iinclude -march=native -Wno-c++2b-extensions -Wno-gnu-string-literal-operator-template -O0 -ggdb -fno-omit-frame-pointer   -no-pie -lCatch2Main -lCatch2 -lfmt -o "build/tests/test_hex"
/nix/store/22p5nv7fbxhm06mfkwwnibv1nsz06x4b-binutils-2.40/bin/ld: /tmp/nix-shell.z2VqNZ/ccCndzcp.o: in function `char* fmt::v9::vformat_to<char*, 0>(char*, fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char> >)':
/nix/store/9kcy2c2zj7i6g190c899wwv2lr518z2n-fmt-9.1.0-dev/include/fmt/core.h:3215: undefined reference to `void fmt::v9::detail::vformat_to<char>(fmt::v9::detail::buffer<char>&, fmt::v9::basic_string_view<char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<std::conditional<std::is_same<fmt::v9::type_identity<char>::type, char>::value, fmt::v9::appender, std::back_insert_iterator<fmt::v9::detail::buffer<fmt::v9::type_identity<char>::type> > >::type, fmt::v9::type_identity<char>::type> >, fmt::v9::detail::locale_ref)'
collect2: error: ld returned 1 exit status
```

I don't have a good guess how to help you diagnose -- any ideas? I can freely try patches or different compiler combinations if you'd like me to. I can also open a new issue if that's what is desired.
