### ISSUE TITLE
arg_id with fmt::arg() and width specifier stopped compiling (since fmt 11.1.0)

### ISSUE THREAD

**Issue by jolz** [fmtlib/fmt#4348]
here's my sample code (based on https://fmt.dev/dev/syntax/ "Box drawing using Unicode fill")
```c++
#include <fmt/core.h>

int main() {
    fmt::print(
        "┌{0:─^{width}}┐\n"
        "│{label: ^{width}}│\n"
        "└{0:─^{width}}┘\n",
        "", fmt::arg("label", "Hello, world!"), fmt::arg("width", 20));

}
```
compile error message with fmt-trunk and -std=c++20: 
```
<source>:4:15:   in 'constexpr' expansion of 'fmt::v11::fstring<const char (&)[1], int, fmt::v11::detail::named_arg<char, char [14]>, fmt::v11::detail::named_arg<char, int> >("\37777777742\37777777624\37777777614{0:\37777777742\37777777624\37777777600^{1}}\37777777742\37777777624\37777777620\012\37777777742\37777777624\37777777602{label: ^{1}}\37777777742\37777777624\37777777602\012\37777777742\37777777624\37777777624{0:\37777777742\37777777624\37777777600^{1}}\37777777742\37777777624\37777777630\012")'
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/base.h:2708:53:   in 'constexpr' expansion of 'fmt::v11::detail::parse_format_string<char, format_string_checker<char, 4, 0, true> >(fmt::v11::basic_string_view<char>(((const char*)s)), fmt::v11::detail::format_string_checker<char, 4, 0, true>(fmt::v11::basic_string_view<char>(((const char*)s)), (fmt::v11::fstring<const char (&)[1], int, fmt::v11::detail::named_arg<char, char [14]>, fmt::v11::detail::named_arg<char, int> >::arg_pack(), fmt::v11::fstring<const char (&)[1], int, fmt::v11::detail::named_arg<char, char [14]>, fmt::v11::detail::named_arg<char, int> >::arg_pack())))'
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/base.h:1624:32: error: 'constexpr void fmt::v11::detail::format_string_checker<Char, NUM_ARGS, NUM_NAMED_ARGS, DYNAMIC_NAMES>::on_error(const char*) [with Char = char; int NUM_ARGS = 4; int NUM_NAMED_ARGS = 0; bool DYNAMIC_NAMES = true]' called in a constant expression
 1624 |         return handler.on_error("unmatched '}' in format string");
      |                ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

- test in godbolt (gcc-14.2, -std=c++20, fmt-trunk) : https://godbolt.org/z/KPTPzcjjb 
- switch to "fmt-11.0.0" to see it working 
- switch to "-std=c++17" to see it working (no consteval)
- last "good" fmt-version : 11.0.2
- first "failed" fmt-version: 11.1.0

**Comment by vitaut** [comment]
Same as #3817.

**Comment by dinomight** [comment]
@vitaut Are you sure this is a duplicate of #3817 ? I'm seeing this same compilation error in this sample. It seems related to dynamic formatting with named arguments. Surprisingly, switching to a runtime format string works.
```cpp
fmt::format("{a:<{size}}", fmt::arg("a", 1), fmt::arg("size", 10));  // Fails to compile.
fmt::format("{a:{size}}", fmt::arg("a", 1), fmt::arg("size", 10));  // Fails to compile.
fmt::format("{a:<10}", fmt::arg("a", 1), fmt::arg("size", 10));  // Compiles and formats correctly.
fmt::format("{:<{}}", 1, 10);  // Compiles and formats correctly.
fmt::format("{0:<{1}}", 1, 10);  // Compiles and formats correctly.
fmt::format(fmt::runtime("{a:<{size}}"), fmt::arg("a", 1), fmt::arg("size", 10));  // Compiles and formats correctly.
```
Things work in 11.0.2, but compile fails in 11.1.3 in VS 17.14 Preview 1.

**Comment by vitaut** [comment]
It is a duplicate and your example is only superficially similar, please open a separate issue.

**Comment by dinomight** [comment]
Created new issue #4360
