### ISSUE TITLE
Can't build with VS 2017 15.8

### ISSUE THREAD

**Issue by ScottLangham** [fmtlib/fmt#846]
I'm having difficulty using fmt with Visual Studio. I'm currently getting errors like the following. I'm trying the latest version of Visual Studio 15.8.2

```
2>c:\dev\fmt\core.h(968): error C2825: 'fmt::v5::internal::get_type<Context,Arg>::value_type': must be a class or namespace when followed by '::'
2>        with
2>        [
2>            Context=context_t,
2>            Arg=const char *
2>        ]
2>c:\dev\fmt\core.h(975): note: see reference to class template instantiation 'fmt::v5::internal::get_type<Context,Arg>' being compiled
2>        with
2>        [
2>            Context=context_t,
2>            Arg=const char *
2>        ]
2>c:\dev\fmt\core.h(1025): note: see reference to function template instantiation 'unsigned __int64 fmt::v5::internal::get_types<Context,const char*,T,const char*,std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>(void)' being compiled
2>        with
2>        [
2>            Context=context_t,
2>            T=int
2>        ]
2>c:\dev\fmt\core.h(1025): note: while compiling class template member function '__int64 fmt::v5::format_arg_store<context_t,const char *,T,const char *,std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>::get_types(void)'
2>        with
2>        [
2>            T=int
2>        ]
2>c:\dev\fmt\core.h(1387): note: see reference to class template instantiation 'fmt::v5::format_arg_store<context_t,const char *,T,const char *,std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>' being compiled
2>        with
2>        [
2>            T=int
2>        ]
2>c:\dev\\formatstring.h(407): note: see reference to function template instantiation 'std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> fmt::v5::format<const wchar_t*,const char*,T,const char*,std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>>,std::basic_string<char,std::char_traits<char>,std::allocator<char>>>(const String &,const char *const &,const T &,const char *const &,const std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> &,const std::basic_string<char,std::char_traits<char>,std::allocator<char>> &)' being compiled
2>        with
2>        [
2>            T=int,
2>            String=const wchar_t *
2>        ]
```

**Comment by ScottLangham** [comment]
Repro sln attached

[FmtTest.zip](https://github.com/fmtlib/fmt/files/2332292/FmtTest.zip)

**Comment by ScottLangham** [comment]
This is possibly something to do with trying to use a wide format string, but formatting in a single byte string argument. This used to work ok in the old version of fmt I was using from a couple of years ago.

**Comment by vitaut** [comment]
Mixing narrow and wide character strings is disallowed for reasons discussed in #606.

**Comment by ScottLangham** [comment]
Ok, thanks very much. I've found I can workaround my case by first passing all the args through a func I can overload to do wide to narrow and vice versa  for various types.
