### ISSUE TITLE
Link error on 6.1.0

### ISSUE THREAD

**Issue by egorpugin** [fmtlib/fmt#1445]
Custom build system, worked fine on 6.0.0 and before, error after 6.1.0 update.
Dll build + build with sources (non header only).
Is there something on my side or it's a bug?

```
error LNK2019: unresolved external symbol "void __cdecl fmt::v6::internal::assert_fail(char const *,int,char const *)" (?assert_fail@internal@v6@fmt@@YAXPEBDH0@Z) referenced in function "class stdext::checked_array_iterator<char *> __cdecl fmt::v6::internal::format_decimal<char,unsigned int,class stdext::checked_array_iterator<char *>,class <lambda_18a81b6c877b6827ad6aa98de427f027> >(class stdext::checked_array_iterator<char *>,unsigned int,int,class <lambda_18a81b6c877b6827ad6aa98de427f027>)" (??$format_decimal@DIV?$checked_array_iterator@PEAD@stdext@@V<lambda_18a81b6c877b6827ad6aa98de427f027>@@@internal@v6@fmt@@YA?AV?$checked_array_iterator@PEAD@stdext@@V34@IHV<lambda_18a81b6c877b6827ad6aa98de427f027>@@@Z)
fatal error LNK1120: 1 unresolved externals
```

**Comment by egorpugin** [comment]
Added FMT_API in core.h and FMT_API in format-inl.h and it worked.

**Comment by vitaut** [comment]
Could you submit a PR?

**Comment by egorpugin** [comment]
Sure.
https://github.com/fmtlib/fmt/pull/1446

**Comment by egorpugin** [comment]
Probably it's worth it to create test that reproduces this issue (dll build). But I don't have time to work on it.
