### ISSUE TITLE
8.0.1 cannot print a tl::unexpected result

### ISSUE THREAD

**Issue by acgetchell** [fmtlib/fmt#2621]
This works in 7.1.3, but fails on 8.0.1 with macOS, linux-gcc, linux-clang, and Windows with Visual Studio 2019:

https://github.com/acgetchell/CDT-plusplus/runs/4344620149?check_suite_focus=true#step:6:11

https://github.com/acgetchell/CDT-plusplus/runs/4344620143?check_suite_focus=true#step:7:21

https://github.com/acgetchell/CDT-plusplus/runs/4344620162?check_suite_focus=true#step:7:11

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/builds/41689641#L3821

The typical error is:

```
Error: /Users/runner/work/CDT-plusplus/CDT-plusplus/tests/Apply_move_test.cpp:105:33: error: call to consteval function 'fmt::basic_format_string<char>::basic_format_string<std::string, 0>' is not a constant expression
      if (!result) { fmt::print(result.error()); }
```

The code which fails is:

https://github.com/acgetchell/CDT-plusplus/blob/develop/tests/Apply_move_test.cpp#L29

Which calls:

https://github.com/acgetchell/CDT-plusplus/blob/develop/include/Apply_move.hpp#L30

**Comment by mwinterb** [comment]
fmt 8 introduced compile time format string checks by default, but it needs
a constexpr format string to do so.
Since error() returns a std::string, it can't parse it to do the checks.
fmt::print has never had the behavior of just writing out the string
provided if the parameter pack is empty.
Just like with printf when dealing with untrusted strings, the print
statement should be `fmt::print("{}", result.error());`

**Comment by acgetchell** [comment]
Thank you for the tip and explanation.
