### ISSUE TITLE
Library fails to compile on Ubuntu 16.04.3 LTS (gcc 5.4.0)

### ISSUE THREAD

**Issue by fo-fo** [fmtlib/fmt#555]
I encountered the following error when trying to compile the library (latest on master, 032c83807f95d83f2355f1c436909bb577b920bc) on Ubuntu 16.04.3 LTS (gcc 5.4.0):

```
In file included from /home/f/Documents/repos/fmt/fmt/format.cc:28:0:
/home/f/Documents/repos/fmt/fmt/format.h:146:23: error: expected unqualified-id before ‘[’ token
 # define FMT_NORETURN [[noreturn]]
                       ^
/home/f/Documents/repos/fmt/fmt/format.h:935:9: note: in expansion of macro ‘FMT_NORETURN’
 FMT_API FMT_NORETURN void report_unknown_type(char code, const char *type);
```

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/37eb419af260898b9543697db4f703cdf670c108, thanks for reporting!
