### ISSUE TITLE
Possible performance regression for doubles

### ISSUE THREAD

**Issue by TD22057** [fmtlib/fmt#2583]
I'm guessing I'm doing something wrong but I'm struggling to figure out what.  We're upgrading from fmt 7.0.3 to 8.0.1 and see a big decrease in performance when formatting doubles.  I've tested with with both g++ 10.2 and 11.2 (on linux) and see similar results.  I've checked the cmake build output and both -O3 and -NDEBUG were defined when building the fmt library.  

On my machine, I get these kind of times for 10,000,000 doubles
```
fmt version 7.0.3
1.625990 sec  fmt::format
1.299081 sec  FMT_COMPILE

fmt version 8.0.1
3.341155 sec  fmt::format
2.892855 sec  FMT_COMPILE
```

Here's the program I ran (compiled with -O3 -NDEBUG -std=c++17).

```
#include <chrono>
#include <iostream>
#include <fstream>
#include <cstdio>
#include <fmt/format.h>
#include <fmt/compile.h>
#include <fmt/printf.h>

int main()
{
   const size_t NUM = 10000000;
   double* v = new double[NUM];
   for ( size_t i = 0; i < NUM; i++ ) v[i] = i;
   std::cout << "Writing " << NUM << " doubles\n";

   const char* out = "out.txt";
   {
      std::ofstream f( out );
      auto t0 = std::chrono::high_resolution_clock::now();
      for ( size_t i = 0; i < NUM; i++ )
      {
         f << fmt::format( "{:22.15e}\n", v[i] );
      }
      auto t1 = std::chrono::high_resolution_clock::now();
      std::chrono::duration<double> dt = t1 - t0;
      std::cout << fmt::format( "{:.6f} sec  fmt::format\n", dt.count() );
      std::remove( out );
   }
      
   {
      std::ofstream f( out );
      auto t0 = std::chrono::high_resolution_clock::now();
      for ( size_t i = 0; i < NUM; i++ )
      {
         f << fmt::format( FMT_COMPILE("{:22.15e}\n"), v[i] );
      }
      auto t1 = std::chrono::high_resolution_clock::now();
      std::chrono::duration<double> dt = t1 - t0;
      std::cout << fmt::format( "{:.6f} sec  FMT_COMPILE\n", dt.count() );
      std::remove( out );
   }

   return 0;
}
```

Any help would be greatly appreciated.  Thanks.
@jrevans

**Comment by ilyapopov** [comment]
I tied your test case and can confirm your results. However, I have also tested versions 7.1.0 and it already shows slow results.

fmt 7.0.3

```
Writing 10000000 doubles
1.216086 sec  fmt::format
0.905413 sec  FMT_COMPILE
```

fmt 7.1.0

```
Writing 10000000 doubles
2.607385 sec  fmt::format
2.327536 sec  FMT_COMPILE
```

**Comment by ilyapopov** [comment]
Main highlight of version 7.1.0 https://github.com/fmtlib/fmt/releases/tag/7.1.0 is switch to different floating point algorithm which supposed to be faster. I guess with your format `{:22.15e}` you are hitting some corner case in the new algorithm.

**Comment by vitaut** [comment]
The switch to a new algorithm was done for the default (shortest) representation so it doesn't apply here.

**Comment by TD22057** [comment]
Thanks.  I tried to run git-bisect to figure out the commit but I can't build 7.0.3 or 7.1.0 with gcc 10 or 11.  I get the following link error no matter what I try:
```
undefined reference to `fmt::v7::detail::vformat[abi:cxx11](fmt::v7::basic_string_view<char>, fmt::v7::format_args)'
```

**Comment by TD22057** [comment]
Got it work:
```
# 3.5 sec  7.1.0
# 2.5 sec  7.0.3
# 3.5 sec  78b594431357d04fc0d6c651cb6e89df3fde3cf5
# 1.95 sec 633213d96fd04da5ebdc524ef373a433aff014dd
# 1.80 sec 6fb7c6fb25e2c0088b4aa5e53a59d8efb2bd3319
# 1.77 sec 5dff01d31bdd0c7690a30066024782fc5d8dd30e
# 1.77 sec bff4d18efba37c0ffd44f036a7adaff1064c840f
# 1.79 sec efe3694f150a1f307d014e68cd88350067769b19
# 3.52 sec 595902f8a0d0730c8b46162b881c4347c77da229
# 3.44 sec 58a044be5d66ef3c3da9408cc17a70cb7380b22e
```
First bad commit:
```
58a044be5d66ef3c3da9408cc17a70cb7380b22e is the first bad commit
commit 58a044be5d66ef3c3da9408cc17a70cb7380b22e
Author: Victor Zverovich <viz@fb.com>
Date:   Fri Sep 11 07:19:37 2020 -0700

    Use built-in FP formatter for any precision

:040000 040000 d5ca93809d38357ab25576b4875c75be8af23d06 aed0ca36a9e9b468650906c59368c5b4309f8dc6 M      include
```

**Comment by TD22057** [comment]
Unfortunately I'm not sure how useful that information is.  While it seems true that commit made it 2x as slow as before, the current `format_float()` code is a lot different than the code before/after that commit.  So the current code is also 2x as slow as before but it's less obvious why or what to do about it.

**Comment by vitaut** [comment]
58a044be5d66ef3c3da9408cc17a70cb7380b22e fixed a bug that incorrectly picked the fast path in some cases when formatting an FP number with high precision. So while it was faster it could produce slightly inaccurate results.

I recommend using the default format when possible. It is faster, shorter and gives you round trip guarantees.
