### ISSUE TITLE
format with custom allocator doesn't compile if replicated from docs

### ISSUE THREAD

**Issue by Orlha** [fmtlib/fmt#2480]
API documentation mentions that it's possible to use a custom allocator by defining custom formatting function.
I've inserted that paragraph from the docs for convenience.

```
using custom_memory_buffer =
  fmt::basic_memory_buffer<char, fmt::inline_buffer_size, custom_allocator>;

using custom_string =
  std::basic_string<char, std::char_traits<char>, custom_allocator>;

custom_string vformat(custom_allocator alloc, fmt::string_view format_str,
                      fmt::format_args args) {
  custom_memory_buffer buf(alloc);
  fmt::vformat_to(buf, format_str, args);
  return custom_string(buf.data(), buf.size(), alloc);
}

template <typename ...Args>
inline custom_string format(custom_allocator alloc,
                            fmt::string_view format_str,
                            const Args& ... args) {
  return vformat(alloc, format_str, fmt::make_format_args(args...));
}
```
This example no longer compiles for me (been using it in a couple of projects for some time) with the following error:
```
error: no matching function for call to ‘vformat_to(custom_memory_buffer&, fmt::v7::string_view&, fmt::v7::format_args&)’
fmt::vformat_to(buf, format_str, args);
```

I've tested it with 8.0.0, 8.0.1 and master (ee63f5f).
It compiles (and works) fine with 7.1.3.
I wasn't able to quickly diagnose the problem further.

**Comment by mwinterb** [comment]
Looks like the fmt.dev/latest documentation just hasn't been updated yet. `vformat_to` no longer has support for formatting to a `basic_memory_buffer` anymore. You'll need to pass the result of `std::back_inserter(buf)` to `vformat_to` instead. That also works with 7.1.3. https://github.com/fmtlib/fmt/commit/e41ac1f875b7a1c419beaf7ddf431a01fb530a92

(That sample should probably also be updated to use `fmt::format_string` instead of `fmt::string_view` to get format string checks in C++20: https://gcc.godbolt.org/z/Gd3h6fdW8)

**Comment by vitaut** [comment]
The documentation has already been updated: https://fmt.dev/dev/api.html#custom-allocators.
