### ISSUE TITLE
Formatting CString no longer works

### ISSUE THREAD

**Issue by AndreaMuccioli** [fmtlib/fmt#1338]
I'm using fmt with a legacy MFC project that uses both std::string in the newer parts and MFC CString in the older ones.
With release 5.3.0 I was able to use both fmt::sprintf and fmt::format with std::string and CString alike.
In new release 6.0.0 I get a compilation error when I try to format a string with a CString.
```c++
#include <iostream>
#include <afxwin.h>
#include <string>

#ifndef FMT_HEADER_ONLY
#define FMT_HEADER_ONLY
#endif

#include "printf.h"
#include "format.h"

int main()
{
	CString foo = "foo";
	std::string bar = fmt::sprintf("%s", foo);
	std::string bar2 = fmt::format("{}", foo);
	std::cout << bar << std::endl;
	std::cout << bar2 << std::endl;
}
```

This code compiles and works fine with release 5.3.0, but gives compile error with 6.0.0.
```
1>------ Build started: Project: ConsoleApplicationFMT, Configuration: Debug Win32 ------
1>ConsoleApplicationFMT.cpp
1>\ConsoleApplicationFMT\core.h(844,1): error C2668:  'fmt::v6::internal::arg_mapper<Context>::map': ambiguous call to overloaded function
1>\ConsoleApplicationFMT\core.h(844,1): error C2668:         with
1>\ConsoleApplicationFMT\core.h(844,1): error C2668:         [
1>\ConsoleApplicationFMT\core.h(844,1): error C2668:             Context=context
1>\ConsoleApplicationFMT\core.h(844,1): error C2668:         ]
1>\ConsoleApplicationFMT\core.h(828,26): message :  could be 'const T &fmt::v6::internal::arg_mapper<Context>::map<Arg,0>(const T &)'
1>\ConsoleApplicationFMT\core.h(828,26): message :         with
1>\ConsoleApplicationFMT\core.h(828,26): message :         [
1>\ConsoleApplicationFMT\core.h(828,26): message :             T=CString,
1>\ConsoleApplicationFMT\core.h(828,26): message :             Context=context,
1>\ConsoleApplicationFMT\core.h(828,26): message :             Arg=CString
1>\ConsoleApplicationFMT\core.h(828,26): message :         ]
1>\ConsoleApplicationFMT\core.h(793,46): message :  or       'fmt::v6::basic_string_view<char> fmt::v6::internal::arg_mapper<Context>::map<Arg,0>(const T &)'
1>\ConsoleApplicationFMT\core.h(793,46): message :         with
1>\ConsoleApplicationFMT\core.h(793,46): message :         [
1>\ConsoleApplicationFMT\core.h(793,46): message :             Context=context,
1>\ConsoleApplicationFMT\core.h(793,46): message :             Arg=CString,
1>\ConsoleApplicationFMT\core.h(793,46): message :             T=CString
1>\ConsoleApplicationFMT\core.h(793,46): message :         ]
1>\ConsoleApplicationFMT\core.h(844,1): message :  while trying to match the argument list '(Arg)'
1>\ConsoleApplicationFMT\core.h(844,1): message :         with
1>\ConsoleApplicationFMT\core.h(844,1): message :         [
1>\ConsoleApplicationFMT\core.h(844,1): message :             Arg=CString
1>\ConsoleApplicationFMT\core.h(844,1): message :         ]
1>\ConsoleApplicationFMT\core.h(1000): message :  see reference to alias template instantiation 'fmt::v6::internal::mapped_type_constant<CString,context>' being compiled
1>\ConsoleApplicationFMT\core.h(1102): message :  see reference to function template instantiation 'unsigned __int64 fmt::v6::internal::encode_types<Context,CString,>(void)' being compiled
1>\ConsoleApplicationFMT\core.h(1102): message :         with
1>\ConsoleApplicationFMT\core.h(1102): message :         [
1>\ConsoleApplicationFMT\core.h(1102): message :             Context=context
1>\ConsoleApplicationFMT\core.h(1102): message :         ]
1>\ConsoleApplicationFMT\printf.h(620): message :  see reference to class template instantiation 'fmt::v6::format_arg_store<context,CString>' being compiled
1>\ConsoleApplicationFMT\ConsoleApplicationFMT.cpp(23): message :  see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> fmt::v6::sprintf<char[3],CString,char>(const S (&),const CString &)' being compiled
1>\ConsoleApplicationFMT\ConsoleApplicationFMT.cpp(23): message :         with
1>\ConsoleApplicationFMT\ConsoleApplicationFMT.cpp(23): message :         [
1>\ConsoleApplicationFMT\ConsoleApplicationFMT.cpp(23): message :             S=char [3]
1>\ConsoleApplicationFMT\ConsoleApplicationFMT.cpp(23): message :         ]
1>\ConsoleApplicationFMT\core.h(999): error C2062:  type 'unknown-type' unexpected
1>\ConsoleApplicationFMT\core.h(1000,46): error C2039:  'value': is not a member of '`global namespace''
1>\ConsoleApplicationFMT\core.h(1101,7): error C3615:  constexpr function 'fmt::v6::internal::encode_types' cannot result in a constant expression
1>\ConsoleApplicationFMT\core.h(1102): message :  failure was caused by control reaching the end of a constexpr function
1>\ConsoleApplicationFMT\core.h(1103,62): error C2131:  expression did not evaluate to a constant
1>\ConsoleApplicationFMT\core.h(1103,62): message :  failure was caused by a read of an uninitialized symbol
1>\ConsoleApplicationFMT\core.h(1103,62): message :  see usage of 'types'
1>Done building project "ConsoleApplicationFMT.vcxproj" -- FAILED.
```

If I explicitly convert the CString to his char array equivalent it obviously works fine again:
`fmt::sprintf("%s",` foo.GetBuffer())`

I'm working with Visual Studio 2019 and msvc142

**Comment by vitaut** [comment]
`CString` was probably working by accident in an older version. In general you should provide a specialization of `formatter` as explained in https://fmt.dev/latest/api.html#formatting-user-defined-types or convert to something printable explicitly e.g. by calling `GetBuffer()`.
