### ISSUE TITLE
Head does not compile in MSVC 16.10.1 with /std:c++latest /Zc:__cplusplus

### ISSUE THREAD

**Issue by Spammed** [fmtlib/fmt#2351]
MSVC 16.10.1 fails to compile current head with `/std:c++latest /Zc:__cplusplus` (-> `#define __cplusplus 201705L`)
but fails not with `/std:c++latest /Zc:__cplusplus-` (-> `#define __cplusplus 199711L`).

Code sample see: https://godbolt.org/z/e7zehe6fG

Compilation fails with message
> format.h(899,29): error C3615: constexpr function 'fmt::v7::detail::count_digits' cannot result in a constant expression
> format.h(904,35): message : failure was caused by variable declaration with non-automatic storage

**Comment by vitaut** [comment]
The godbolt example compiles successfully. Was it supposed to demonstrate an error?

**Comment by DanielaE** [comment]
I ran into the same problem.
Fixed with #2352

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/3423d75475d213cadcc512e6dc78a7805ab1ed9d. That piece of code is going away completely soon.

**Comment by DanielaE** [comment]
Oh well, it took me ages to find out why gcc would fail to compile all of the time ...

**Comment by Spammed** [comment]
Sorry, my code example should show the error, but not on Godbolt.

In addition, I have been fooled by Visual Studio:
In Visual Studio 16.10.1 (or 16.11 Preview 1.0) the compiler and Intellisense do not quite agree about `__cplusplus`:
Intellisense thinks `__cpluplus` would be '`201705`', but the compiled program outputs '`202004`'.
What a mess!
