### PR TITLE
Fix unresolved reference error

### PR DESCRIPTION
**Pull request by Kurkin**
I'm using {fmt} in not header-only mode. After upgrade to 7.0.0 build is broken due to unresolved reference.
```
error LNK2001: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl fmt::v6::detail::vformat(class fmt::v6::basic_string_view<char>,struct fmt::v6::format_args)"
```

I agree that my contributions are licensed under the {fmt} license, and agree to future changes to the licensing.

### CODE REVIEW

**Comment by vitaut** [comment]
Thank you!
