### ISSUE TITLE
Partial specialization of formatter<string> after instantiation in gcc

### ISSUE THREAD

**Issue by zptan** [fmtlib/fmt#3584]
### Error
```
bazel-out/k8-opt/bin/external/fmt/libfmt/include/fmt/format.h:4076:1: error: partial specialization of 'struct fmt::v10::formatter<std::__cxx11::basic_string<_CharT>, Char>' after instantiation of 'struct fmt::v10::formatter<std::__cxx11::basic_string<char>, char, void>' [-fpermissive]
 4076 | FMT_FORMAT_AS(std::basic_string<Char>, basic_string_view<Char>);
      | ^~~~~~~~~~~~~
bazel-out/k8-opt/bin/external/fmt/libfmt/include/fmt/format.h:4078:1: error: partial specialization of 'struct fmt::v10::formatter<std::basic_string_view<Char>, Char>' after instantiation of 'struct fmt::v10::formatter<std::basic_string_view<char>, char, void>' [-fpermissive]
 4078 | FMT_FORMAT_AS(detail::std_string_view<Char>, basic_string_view<Char>);
      | ^~~~~~~~~~~~~
```

### Env
OS: Ubuntu 22.04.3
Compiler: g++ 11.4.0

**Comment by vitaut** [comment]
Please provide a godbolt repro.

**Comment by alex-700** [comment]
@vitaut 

we faced the same problem too. 

There is a minimal reproducer I was able to craft:
https://godbolt.org/z/dhjah7PMT

It compiles (e.g) in
- clang + c++20 + fmt/10.1.0
- clang + c++17 + fmt/10.1.0
- gcc + c++20 + fmt/10.0.0
- gcc + c++17 + fmt/10.1.0

Failes:
- gcc + c++20 + fmt/10.1.0

**Comment by vitaut** [comment]
Thanks for the repro, reopened the issue.

**Comment by pauldreik** [comment]
I git bisected this to commit https://github.com/fmtlib/fmt/commit/256a826d6305dd1ee7998acb9bc29e3ef9e1b723

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/bbb784fb1b9dc35f9dbbe32a3a43c8b725d889a6. Thanks for reporting.

**Comment by windowsair** [comment]
Same issue. On older versions of fmtlib, moving `#include <fmt/format.h>` before `#include <fmt/core.h>` temporarily solves the problem.

**Comment by tocic** [comment]
Experiencing a similar issue with [this test project](https://godbolt.org/#z:OYLghAFBqd5QCxAFwE4FN0BoCWIIDGAtgIYDW6AgqsAM4gDkAtACIDCAspQNICiA%2BgCEAqgEkAMi34AVAJoAFXgFIAzCxboARgFdgDLAQD2RAA44ANulTiSAO2DaSwdKIAmIAkoBMg74IPatMjGAPLayCbhAGIW6LYkROgoCOj86AAe6AThJJqWWABmsfSw6K44wahuIABshbHVAIwALPWW8YkgpDi2AHQEJiZYoAz6OLSitgTm2q5ljAAMY7QcJD0AyobaqARJDI3LISZxi/rmdsDVowCUWBBlFYZV7kyNbS7ujQCs7x1JnOR0OJxshaL1kOlkMNGMRAfwiD0cERtER%2BBgAI7aHAYVwQABqvAASutRCEAHIAahUvUaC2uSgWlAZlBMqEMACsssgILQECRjrR6YzmSRXK5%2BOYcJpUCRUABPCCSzQUpX9QYqqW9BBCyjIWXOZASnpkI3S2U4dC0RVSinyQmiPGUaS8CkFIjIVw6kVitKZbJ6vLoCDIFK%2BrI5QMU7p9AYmHV6mjoQ2S2wmpUy1AWq0h1IZcMByy2%2B2O50a5Vuj065aTaazeYMJa4FZrWybba7U5No4nfZnC7VWEUW73cqVaoqd5NACcvwSSVVsehoybNZmc3cDeWqw2Wx2ewOXeOtk753sVwYw4eY/crSKlmqXgWs86qoQS%2BrUzX9cb423rd3Ha9oePaNqelwbhetzjACFDyGynIEMgnbsiAby2OgADuMT3u4XiNLc5iMF8%2BjHpuWCGIw0gYOgFLeCoB5IZu1y3GQICPr0XzNAA7FOzRfI%2BnE8XxrSEQwzQkZ2FHLvQT6MUsw4wFAikQEgRhzLwo5PLg%2BB3nEc5dC2apDAUhi2Mg6wECQliobepnIMItDoPI6TIbUWBgR4fh%2BFgjmWIhOCmfgcSuGwhgzEQx5vMFwLoWSKKaFYIAABxYCYhi0BUAW2KF4WRal6WZaZMXoHFRAJagyU%2BegfnIFl6wJsgOUonlvlcnVDXFaV5WVUEsqNWFzWoT5HU9CV8WJUlty0ABex0T0tZzLRXheK%2B3heMyG1eCo81frRKhsBWAD0RgYFqqjKMKjI9MgUYthA1y0VxviMhSr2uu6IAgKy10QGtShPSAABUShfLwKgLP9LAg2wthrVgFLIJaSEgEyT2Q/SKjPajUOMhe7lERJZEUdGRlYHJeMqR4hjqZpqDaRAul/CAC6DIUdkWVZSQtGzZkOU5LlkShE4eZ4Pjea1/mBfctghQNEVsVg0WjV1iWNBOaUZbVplNfLXj5ZrWWdeNFVq1VNXtX1OvHnrEta62I2xcbqETr1qD9blCuu8gRtlarKhTTNjBzZ%2BdZLStmoIH9l1MltO2h6obBBJm9jnRtwqxyHi0J0dJmoKQyBnSoF1Moyfy0CYJC7O9N3/VjIrhIYrpPPniOoAniNBJ9TJF59uf54QplBAjSNd94NQUiQ8N9yQhpGGZGTIGPFKIekD1z0PTDnU3ecz/wc%2BI5Cn0VFYM9PI9WNvRSGDINstjby3VgJ0E7ggEnPTAOdvfNzPEAkOChj8DfvYe68MV4YzrlxHGJdsZ41EsRLApFGwURZkMcmw5VLU3QBpR4dM8AM1iEzV8PNzKWWstzEyvNHLOVciJC4nkxY%2BDNm1KWwUraoRSkrR2vsKo/A1oVbKctIopT4XbH23Ufi2wtm7NhjQUqSNMvVPqYjEoSIajIuRDsxrcJAF8AO7ZZpbVZE4UgFJTK7DTjHbamcaLZ3dMdJ46BC7F02lYhaNj9pAI/kXCxZcK5Vw7jXNG0ck7aEQhSSg59mSX2uhPPaLAKSNC2qoOuL03okAbgjABnj7rL0HjdTeRcKTP0%2Bp4yJqTL6vWvrfIpHpPrBEAWgd%2Bv9wFRLepDDakDkkWPadHXxlcaIVjKdAxGphziIz2mwVOjIQlhOnsgVu7cR4oy3iAe%2BM8FkeNqa/RpKdCm11aa9dJwQ1ncnXjdAJo8vDj0nicvedkF5LzAbk2wG8t5zLufPQ%2BIBj4ykqF04UnTMbdMga9Q6h0KR9KrhWCxsCCYIMkszCOZNTjMSwCkUUiUQGsWaElXozR8UEsJYS/GYl9BEB0U%2BRB%2BgpL6HoHrNBdxlLKQwaYWIuD8BGFZZYCqwBEkTjvK3egEBNCdk0D0WUcpGAHjFfEeUIRNAIUYgeTliQzIhFsOYSVZE5g6GAGwKy5h6BATmKQew1ltXYjagAN0tJ2PM/o9g/nnqJUCUoMxylCnMTsjTyVARtagTQ6V0AaFNcAFMIx5KFHOHQPEFoMLdlIgeChJDOY2WIXzahgsQDCzoaLXwjClQlCgEzCsWB/VSoWHhSC5ETB2yNUwZ%2BqgWB5r8I%2Bal/rMxzCLVNaqzDjzS1lh7KKMtlEm31vwmR47RHKydm8eR9tLaCKGvOxRbtR3LrUUuudmiVYm1uGgTAqECJwqpeRRgFJ0hJRqEwGozQKTAAIAQBJXhegqApBAKimAlr0WuPoNBtx0VzAqlinR1JOI1AWFOKcXgpwLC4klBYasRKMHElgclVzegLAWF8Li3FEm3pUDUeD8KiaMFpSAWSKLGXwEplsCI4R6bJo5mQ2ylD%2BauQnAe9AOBPhYAwjKEwUrYUMHgaeqSYR6M3UMAUC9V6b13ofU%2BxJr732hS5VYb9/s/0ooA%2BgDFwHj2krQyALi1IoPNC8PxJKpmvg1BUFtEjSCyM%2BQo8ipiLEdGNA4l8Hzvm/M%2BbqKJFQhMnPLn/VgViPE8X8Ww9xXiMXbMkq8GS1CWHHPUuc%2BF0SyX0tnrCzpstVgMqBWaEAA%3D%3D). Interestingly, it works in 10.0.0 and trunk, but doesn't work in 10.1.1 and 10.2.1. If this is expected (i.e. fixed on trunk), could you please provide a new release?

**Comment by vitaut** [comment]
@tocic your example is incorrect: you should include `fmt/format.h` where `formatter<string>` is defined.

**Comment by tocic** [comment]
You mean in `lib.h`? I thought that I can use `fmt/core.h` in headers and `fmt/format.h` in sources to reduce the compilation time. Does the second example from [the docs](https://fmt.dev/latest/api.html#formatting-user-defined-types) applies only to `std::string_view`? Maybe I should use `const char*` instead?

> Note that `formatter<string_view>::format` is defined in `fmt/format.h` so it has to be included in the source file.

**Comment by vitaut** [comment]
@tocic, the docs should be clearer about it but let's continue the discussion in #3942 since it's not directly related to the current issue.
