### ISSUE TITLE
compilation broken since commit 2b6f7fc7

### ISSUE THREAD

**Issue by moiwi** [fmtlib/fmt#2771]
Since commit 2b6f7fc7 (Add partial support for extended precision FP) I get these errors compiling format.cc with gcc 8.1:

```
t:\fmt.org\include\fmt\format-inl.h: In instantiation of 'constexpr bool fmt::v8::detail::fp::assign(Float) [with Float = long double; typename std::enable_if<std::integral_constant<bool, (((sizeof (Float) == sizeof (unsigned int)) || (sizeof (Float) == (2 * sizeof (unsigned int)))) || (std::numeric_limits<_Tp>::digits == 64))>::value, int>::type <anonymous> = 0]':
t:\fmt.org\include\fmt\format-inl.h:245:66:   required from 'constexpr fmt::v8::detail::fp::fp(Float) [with Float = long double]'
t:\fmt.org\include\fmt\format-inl.h:2264:30:   required from 'int fmt::v8::detail::format_float(T, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&) [with T = long double]'
../../fmt.org/src/format.cc:111:64:   required from here
t:\fmt.org\include\fmt\format-inl.h:260:24: error: cannot convert 'long long unsigned int' to 'const carrier_uint' {aka 'const fmt::v8::detail::uint128_t'} in initialization
     const carrier_uint significand_mask = implicit_bit - 1;
                        ^~~~~~~~~~~~~~~~
t:\fmt.org\include\fmt\format-inl.h:262:11: error: no match for 'operator&' (operand types are 'fmt::v8::detail::uint128_t' and 'const carrier_uint' {aka 'const fmt::v8::detail::uint128_t'})
     f = u & significand_mask;
         ~~^~~~~~~~~~~~~~~~~~
t:\fmt.org\include\fmt\format-inl.h:264:29: error: no match for 'operator&' (operand types are 'fmt::v8::detail::uint128_t' and 'fmt::v8::detail::dragonbox::float_info<long double, void>::carrier_uint' {aka 'fmt::v8::detail::uint128_t'})
         static_cast<int>((u & exponent_mask<Float>()) >>
                          ~~~^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from t:\fmt.org\include\fmt\format-inl.h:29,
                 from ../../fmt.org/src/format.cc:8:
t:\fmt.org\include\fmt\format.h: In instantiation of 'constexpr typename fmt::v8::detail::dragonbox::float_info<T>::carrier_uint fmt::v8::detail::exponent_mask() [with T = long double; typename fmt::v8::detail::dragonbox::float_info<T>::carrier_uint = fmt::v8::detail::uint128_t]':
t:\fmt.org\include\fmt\format-inl.h:264:51:   required from 'constexpr bool fmt::v8::detail::fp::assign(Float) [with Float = long double; typename std::enable_if<std::integral_constant<bool, (((sizeof (Float) == sizeof (unsigned int)) || (sizeof (Float) == (2 * sizeof (unsigned int)))) || (std::numeric_limits<_Tp>::digits == 64))>::value, int>::type <anonymous> = 0]'
t:\fmt.org\include\fmt\format-inl.h:245:66:   required from 'constexpr fmt::v8::detail::fp::fp(Float) [with Float = long double]'
t:\fmt.org\include\fmt\format-inl.h:2264:30:   required from 'int fmt::v8::detail::format_float(T, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&) [with T = long double]'
../../fmt.org/src/format.cc:111:64:   required from here
t:\fmt.org\include\fmt\format.h:1271:20: error: no match for 'operator<<' (operand types are 'uint' {aka 'fmt::v8::detail::uint128_t'} and 'const int')
   return ((uint(1) << dragonbox::float_info<T>::exponent_bits) - 1)
           ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by vitaut** [comment]
I was not able to repro it on https://godbolt.org/z/rza3b9KfE. Could you provide more details (ideally a godbolt repro)?

**Comment by moiwi** [comment]
The error seems to be due to 32 bit mode (https://godbolt.org/z/5c5bx9vfT)

**Comment by vitaut** [comment]
Should be fixed in https://github.com/fmtlib/fmt/commit/ce93a66dfbf99fe270bca0b6eaf50ce6bbbbc740. Thanks for reporting.
