### ISSUE TITLE
Compilation error << overloading with fmt >7.0

### ISSUE THREAD

**Issue by lukasberbuer** [fmtlib/fmt#2093]
Following code doesn't compile with fmt version >7.0. It seems to be related to issue [1925](https://github.com/fmtlib/fmt/issues/1925), but I couldn't figure out a suitable solution based on ostream overloadings.

Example in Compiler Explorer with different versions:
- [fmt 7.0](https://godbolt.org/z/cYhraY) - works!
- [fmt trunk](https://godbolt.org/z/qqqoMo) - compile error (see output below)

```cpp
#include <iostream>
#include <string>
#include <string_view>
#include <vector>

#include <fmt/core.h>
#include <fmt/ostream.h>

template <typename T>
std::ostream& operator<<(std::ostream& out, const std::vector<T>& v) {
    out << "[";
    for (auto it = v.begin(); it != v.end(); ++it) {
        out << *it;
        if (std::next(it) != v.end()) {
            out << ", ";
        }
    }
    out << "]";
    return out;
}

struct Logger {
    static void log(std::string_view msg) {
        std::cout << msg << std::endl;
    }

    template <typename... Args>
    static void log(std::string_view format, const Args&... args) {
        log(fmt::format(format, args...));
    }
};

int main() {
    std::vector<float> vec {1, 2, 3, 4, 5};

    Logger::log("Basic message");
    Logger::log("Number: {:d}", 5);
    Logger::log("Number: {}", vec);

    return 0;
}
```

Error:
```
In file included from <source>:6:
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/core.h: In instantiation of 'int fmt::v7::detail::check(fmt::v7::detail::unformattable) [with T = std::vector<float>]':
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/core.h:1459:18:   required from 'constexpr fmt::v7::detail::value<Context> fmt::v7::detail::make_arg(const T&) [with bool IS_PACKED = true; Context = fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>; fmt::v7::detail::type <anonymous> = fmt::v7::detail::type::custom_type; T = std::vector<float>; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]'
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/core.h:1571:64:   required from 'constexpr fmt::v7::format_arg_store<Context, Args>::format_arg_store(const Args& ...) [with Context = fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<char>, char>; Args = {const std::vector<float, std::allocator<float> >}]'
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/core.h:1608:18:   required from 'fmt::v7::format_arg_store<fmt::v7::basic_format_context<fmt::v7::detail::buffer_appender<Char>, Char>, fmt::v7::remove_reference_t<Args>...> fmt::v7::make_args_checked(const S&, fmt::v7::remove_reference_t<Args>& ...) [with Args = {const std::vector<float, std::allocator<float> >&}; S = std::basic_string_view<char>; Char = char]'
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/core.h:1890:54:   required from 'std::__cxx11::basic_string<Char> fmt::v7::format(const S&, Args&& ...) [with S = std::basic_string_view<char>; Args = {const std::vector<float, std::allocator<float> >&}; Char = char; typename std::enable_if<((!0) || (! std::is_same<Char, char>::value)), int>::type <anonymous> = 0]'
<source>:29:24:   required from 'static void Logger::log(std::string_view, const Args& ...) [with Args = {std::vector<float, std::allocator<float> >}; std::string_view = std::basic_string_view<char>]'
<source>:38:34:   required from here
/opt/compiler-explorer/libs/fmt/trunk/include/fmt/core.h:1444:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1444 |       formattable<T>(),
      |       ^~~~~~~~~~~~~~~~
```

**Comment by vitaut** [comment]
This is the same as #486. In general you shouldn't be overloading `operator<<` for types in `std` (but if you do it has to be in the same namespace).

**Comment by lukasberbuer** [comment]
Thank you! Just out of curiosity: If it's a lookup issue, why does it work with fmt <=7.0 though?

**Comment by vitaut** [comment]
It worked by accident since earlier version didn't implement proper checks of formattability.
