### ISSUE TITLE
buffered_file::operator=(buffered_file&& other) is annotated as FMT_NOEXCEPT but calls close

### ISSUE THREAD

**Issue by 0x8000-0000** [fmtlib/fmt#1422]
https://github.com/fmtlib/fmt/blob/4afb39bc242b7b7bdf852936f8fd7495d485695a/include/fmt/posix.h#L161

buffered_file::operator=(buffered_file&& other) is annotated as FMT_NOEXCEPT but calls close, which rightly is not annotated as FMT_NOEXCEPT because it throws .

**Comment by 0x8000-0000** [comment]
Found with [cppcheck](https://github.com/danmar/cppcheck) 1.89

**Comment by 0x8000-0000** [comment]
Also G++ 9.2 reports it as an error with -pedantic

fmt/src/posix.cc:119:6: error: declaration of ‘void fmt::v6::file::close()’ has a different exception specifier                                      119 | void file::close() {                                                                                                                                                                        |      ^~~~                                                                                                                                                                             fmt/src/posix.cc:13:                                                                                                         fmt/posix.h:238:16: note: from previous declaration ‘void fmt::v6::file::close() noexcept’                                               238 |   FMT_API void close() FMT_NOEXCEPT;                                                                                                                                                        |                ^~~~~

**Comment by 0x8000-0000** [comment]
Introduced in bb0c8bfea8608670063e7bd549279f630a5f4ede
