### ISSUE TITLE
Unable to print thread id after updating Visual Studio 2022 to 17.2.0

### ISSUE THREAD

**Issue by tksuoran** [fmtlib/fmt#2897]
Solution for #824 no longer compiles:

```C++
#include <thread>
#include <fmt/format.h>
#include <fmt/ostream.h>

int main() {
    fmt::print("main thread id: {}\n", std::this_thread::get_id());
}
```

Compiler output:
```
1>------ Build started: Project: foo, Configuration: Debug x64 ------
1>debug.cpp
1>fmt-src\include\fmt\core.h(1725): error C2338: static_assert failed: 'Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt'
1>fmt-src\include\fmt\core.h(1744): note: see reference to function template instantiation 'fmt::v8::detail::value<Context> fmt::v8::detail::make_value<Context,std::thread::id&>(T)' being compiled
1>        with
1>        [
1>            Context=fmt::v8::format_context,
1>            T=std::thread::id &
1>        ]
1>fmt-src\include\fmt\core.h(1863): note: see reference to function template instantiation 'fmt::v8::detail::value<Context> fmt::v8::detail::make_arg<true,Context,fmt::v8::detail::type::custom_type,std::thread::id&,0>(T)' being compiled
1>        with
1>        [
1>            Context=fmt::v8::format_context,
1>            T=std::thread::id &
1>        ]
1>fmt-src\include\fmt\core.h(1886): note: see reference to function template instantiation 'fmt::v8::format_arg_store<fmt::v8::format_context,std::thread::id>::format_arg_store<std::thread::id&>(std::thread::id &)' being compiled
1>fmt-src\include\fmt\core.h(1886): note: see reference to function template instantiation 'fmt::v8::format_arg_store<fmt::v8::format_context,std::thread::id>::format_arg_store<std::thread::id&>(std::thread::id &)' being compiled
1>fmt-src\include\fmt\core.h(3263): note: see reference to function template instantiation 'fmt::v8::format_arg_store<fmt::v8::format_context,std::thread::id> fmt::v8::make_format_args<fmt::v8::format_context,std::thread::id&>(std::thread::id &)' being compiled
1>foo.cpp(6): note: see reference to function template instantiation 'void fmt::v8::print<std::thread::id>(fmt::v8::basic_format_string<char,std::thread::id>,std::thread::id &&)' being compiled
1>Done building project "foo.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

**Comment by vitaut** [comment]
Added a formatter for `thread::id` in https://github.com/fmtlib/fmt/commit/6bf039d7507504d001dd69f75c59e2204d5278b5.
