### ISSUE TITLE
VisualStudio 15.7 expression did not evaluate to a constant

### ISSUE THREAD

**Issue by sephirostoy** [fmtlib/fmt#749]
The following code does not compile in Visual Studio 15.7, with C++17 and /permissive- flags:
```cpp
#include "fmt/format.h"

int main()
{
    std::string s = format(fmt("{:s}"), "some string");
    return 0;
}
```

> fmt\format.h(2073): error C2131: expression did not evaluate to a constant

**Comment by vitaut** [comment]
What is _MSC_VER on this version?

**Comment by sephirostoy** [comment]
_MSC_VER = 1914.
