### ISSUE TITLE
Latest main tries to link f(un)lockfile even with FMT_OS OFF

### ISSUE THREAD

**Issue by glebm** [fmtlib/fmt#4189]
I've tried updating libfmt to the latest git (https://github.com/diasurgical/devilutionX/pull/7457) and it appears the current version attempts to link f(un)lockfile even with `set(FMT_OS OFF)`.

https://github.com/diasurgical/devilutionX/actions/runs/11191322109/job/31114078447?pr=7457

```
 /opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /tmp/ccd8bZAp.ltrans51.ltrans.o: in function `fmt::v11::vprint(__sFILE*, fmt::v11::basic_string_view<char>, fmt::v11::basic_format_args<fmt::v11::context>) [clone .constprop.0]':
/__w/devilutionX/devilutionX/build/_deps/libfmt-src/include/fmt/format-inl.h:1679:(.text._ZN3fmt3v116vprintEP7__sFILENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_7contextEEE.constprop.0+0x30): undefined reference to `flockfile'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /__w/devilutionX/devilutionX/build/_deps/libfmt-src/include/fmt/format-inl.h:1688:(.text._ZN3fmt3v116vprintEP7__sFILENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_7contextEEE.constprop.0+0xc4): undefined reference to `funlockfile'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/14.2.0/../../../../arm-none-eabi/bin/ld: /tmp/ccd8bZAp.ltrans51.ltrans.o:/__w/devilutionX/devilutionX/build/_deps/libfmt-src/include/fmt/format-inl.h:1688:(.text._ZN3fmt3v116vprintEP7__sFILENS0_17basic_string_viewIcEENS0_17basic_format_argsINS0_7contextEEE.constprop.0+0xe4): undefined reference to `funlockfile'
```

**Comment by glebm** [comment]
Looks like there was a similar issue previously (#4054) that got fixed and has now regressed.

Perhaps the detection mechanism broke.

**Comment by glebm** [comment]
It is also possible that something broken in the open-sources SDKs (e.g. they started declaring f(un)lockfile without defining them) but it is a bit unusual that it would change in 3 of them:

![image](https://github.com/user-attachments/assets/be9f1fc5-c467-49b4-8bda-f9d4a50561b9)

**Comment by glebm** [comment]
Bisecting..

**Comment by glebm** [comment]
439b6d7212d588bc4be890c17f50d4cbf19233a6 is the first bad commit
```
commit 439b6d7212d588bc4be890c17f50d4cbf19233a6
Author: Victor Zverovich <viz@meta.com>
Date:   Sun Jul 21 08:05:07 2024 -0700

    Reenable print optimization

 include/fmt/format-inl.h | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by glebm** [comment]
Looks like these platforms declare but do not define `f(un)lockfile`.

Worked around with:
```cmake
if(NINTENDO_3DS OR NINTENDO_SWITCH OR VITA)
  target_compile_definitions(fmt PUBLIC FMT_USE_FALLBACK_FILE=1)
endif()
```

**Comment by Ghabry** [comment]
FYI: I just updated fmtlib for a homebrew and encountered the same linker error but only for PsVita.

Looks like this is now implemented for 3DS and Switch.

**Comment by KKhanhH** [comment]
@Ghabry It seems to work on the homebrew version of Switch only if there aren't any template instantiations of fmt::print, even with the above preprocessor defines. I don't think the stdio implementation has flock/flockfile or has them undeclared.
