### ISSUE TITLE
Failing to build on Clang 8.0.1

### ISSUE THREAD

**Issue by SnapperTT** [fmtlib/fmt#1266]
Reported errors:

```
./extlib/include/fmt/core.h:1101:19: error: constexpr variable 'types' must be initialized by a constant expression
      is_packed ? internal::encode_types<Context, Args...>()
```

```
In file included from ./extlib/include/fmt/format.h:41:
./extlib/include/fmt/core.h:1103:54: error: constexpr variable 'TYPES' must be initialized by a constant expression
  FMT_DEPRECATED static constexpr unsigned long long TYPES = types;
```
Appears to be clang's hyper strict constexpr handling

```
./extlib/include/fmt/core.h:844:50: error: call to member function 'map' is ambiguous
    type_constant<decltype(arg_mapper<Context>().map(std::declval<T>()))
```
```
./extlib/include/fmt/core.h:1015:32: error: call to member function 'map' is ambiguous
  return arg_mapper<Context>().map(val);
```
arg_mapper<Context>().map(...) appears to not be working

Full compiler tantrum:
```
In file included from ./extlib/include/fmt/format.h:41:
./extlib/include/fmt/core.h:1103:54: error: constexpr variable 'TYPES' must be initialized by a constant expression
  FMT_DEPRECATED static constexpr unsigned long long TYPES = types;
                                                     ^       ~~~~~
./extlib/include/fmt/core.h:1103:62: note: initializer of 'types' is not a constant expression
  FMT_DEPRECATED static constexpr unsigned long long TYPES = types;
                                                             ^
./extlib/include/fmt/core.h:1100:39: note: declared here
  static constexpr unsigned long long types =
                                      ^
./extlib/include/fmt/core.h:1015:32: error: call to member function 'map' is ambiguous
  return arg_mapper<Context>().map(val);
         ~~~~~~~~~~~~~~~~~~~~~~^~~
./extlib/include/fmt/core.h:1106:25: note: in instantiation of function template specialization 'fmt::v5::internal::make_arg<true,
      fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::buffer<char> >, char>, INPUT_ENUM, 0>' requested here
      : data_{internal::make_arg<is_packed, Context>(args)...} {}
                        ^
./extlib/include/fmt/core.h:1285:10: note: in instantiation of member function
      'fmt::v5::format_arg_store<fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::buffer<char> >, char>, const
      INPUT_ENUM>::format_arg_store' requested here
  return {args...};
         ^
./extlib/include/fmt/core.h:1410:20: note: in instantiation of function template specialization 'fmt::v5::internal::make_args_checked<const INPUT_ENUM &,
      fmt::v5::basic_string_view<char>, char>' requested here
         internal::make_args_checked<Args...>(format_str, args...));
                   ^
temp/mcclient/controllers/../fmtWrapper.hh:11:8: note: in instantiation of function template specialization 'fmt::v5::print<fmt::v5::basic_string_view<char>,
      const INPUT_ENUM &, 0>' requested here
                fmt::print(format, args...);
                     ^
temp/mcclient/controllers/uixController.cpp:20:8: note: in instantiation of function template specialization 'fmt::println<INPUT_ENUM>' requested here
                fmt::println ("UxController onInputCallback {}", tag);
                     ^
./extlib/include/fmt/core.h:760:26: note: candidate function
  FMT_CONSTEXPR unsigned map(unsigned short val) { return val; }
                         ^
./extlib/include/fmt/core.h:761:21: note: candidate function
  FMT_CONSTEXPR int map(int val) { return val; }
                    ^
./extlib/include/fmt/core.h:757:21: note: candidate function
  FMT_CONSTEXPR int map(signed char val) { return val; }
                    ^
./extlib/include/fmt/core.h:758:26: note: candidate function
  FMT_CONSTEXPR unsigned map(unsigned char val) { return val; }
                         ^
./extlib/include/fmt/core.h:759:21: note: candidate function
  FMT_CONSTEXPR int map(short val) { return val; }
                    ^
./extlib/include/fmt/core.h:762:26: note: candidate function
  FMT_CONSTEXPR unsigned map(unsigned val) { return val; }
                         ^
./extlib/include/fmt/core.h:763:27: note: candidate function
  FMT_CONSTEXPR long_type map(long val) { return val; }
                          ^
./extlib/include/fmt/core.h:764:28: note: candidate function
  FMT_CONSTEXPR ulong_type map(unsigned long val) { return val; }
                           ^
./extlib/include/fmt/core.h:765:27: note: candidate function
  FMT_CONSTEXPR long long map(long long val) { return val; }
                          ^
./extlib/include/fmt/core.h:766:36: note: candidate function
  FMT_CONSTEXPR unsigned long long map(unsigned long long val) { return val; }
                                   ^
./extlib/include/fmt/core.h:767:22: note: candidate function
  FMT_CONSTEXPR bool map(bool val) { return val; }
                     ^
./extlib/include/fmt/core.h:777:24: note: candidate function
  FMT_CONSTEXPR double map(float val) { return static_cast<double>(val); }
                       ^
./extlib/include/fmt/core.h:778:24: note: candidate function
  FMT_CONSTEXPR double map(double val) { return val; }
                       ^
./extlib/include/fmt/core.h:779:29: note: candidate function
  FMT_CONSTEXPR long double map(long double val) { return val; }
                            ^
./extlib/include/fmt/core.h:806:29: note: candidate function not viable: no known conversion from 'const INPUT_ENUM' to 'const void *' for 1st argument; take
      the address of the argument with &
  FMT_CONSTEXPR const void* map(const void* val) { return val; }
                            ^
./extlib/include/fmt/core.h:781:34: note: candidate function not viable: no known conversion from 'const INPUT_ENUM' to
      'fmt::v5::internal::arg_mapper<fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::buffer<char> >, char> >::char_type *'
      (aka 'char *') for 1st argument
  FMT_CONSTEXPR const char_type* map(char_type* val) { return val; }
                                 ^
./extlib/include/fmt/core.h:782:34: note: candidate function not viable: no known conversion from 'const INPUT_ENUM' to 'const
      fmt::v5::internal::arg_mapper<fmt::v5::basic_format_context<std::__1::back_insert_iterator<fmt::v5::internal::buffer<char> >, char> >::char_type *'
      (aka 'const char *') for 1st argument
  FMT_CONSTEXPR const char_type* map(const char_type* val) { return val; }
                                 ^
./extlib/include/fmt/core.h:796:29: note: candidate function not viable: no known conversion from 'const INPUT_ENUM' to 'const signed char *' for 1st argument
  FMT_CONSTEXPR const char* map(const signed char* val) {
                            ^
./extlib/include/fmt/core.h:800:29: note: candidate function not viable: no known conversion from 'const INPUT_ENUM' to 'const unsigned char *' for 1st argument
  FMT_CONSTEXPR const char* map(const unsigned char* val) {
                            ^
./extlib/include/fmt/core.h:805:29: note: candidate function not viable: no known conversion from 'const INPUT_ENUM' to 'void *' for 1st argument
  FMT_CONSTEXPR const void* map(void* val) { return val; }
                            ^
./extlib/include/fmt/core.h:807:29: note: candidate function not viable: no known conversion from 'const INPUT_ENUM' to 'std::nullptr_t' (aka 'nullptr_t') for
      1st argument
  FMT_CONSTEXPR const void* map(std::nullptr_t val) { return val; }
                            ^
./extlib/include/fmt/core.h:770:27: note: candidate template ignored: requirement 'is_char<INPUT_ENUM>::value' was not satisfied [with T = INPUT_ENUM]
  FMT_CONSTEXPR char_type map(T val) {
                          ^
./extlib/include/fmt/core.h:784:46: note: candidate template ignored: requirement 'is_string<INPUT_ENUM>::value' was not satisfied [with T = INPUT_ENUM]
  FMT_CONSTEXPR basic_string_view<char_type> map(const T& val) {
                                             ^
./extlib/include/fmt/core.h:793:46: note: candidate template ignored: requirement 'std::is_constructible<fmt::v5::basic_string_view<char>, INPUT_ENUM>::value'
      was not satisfied [with T = INPUT_ENUM]
  FMT_CONSTEXPR basic_string_view<char_type> map(const T& val) {
                                             ^
./extlib/include/fmt/core.h:808:43: note: candidate template ignored: could not match 'const T *' against 'INPUT_ENUM'
  template <typename T> FMT_CONSTEXPR int map(const T*) {
                                          ^
./extlib/include/fmt/core.h:821:21: note: candidate template ignored: requirement 'std::is_enum<INPUT_ENUM>::value' was not satisfied [with T = INPUT_ENUM]
  FMT_CONSTEXPR int map(const T& val) {
                    ^
./extlib/include/fmt/core.h:828:26: note: candidate template ignored: requirement '!is_string<INPUT_ENUM>::value && !is_char<INPUT_ENUM>::value &&
      (is_constructible<fmt::v5::formatter<INPUT_ENUM, char, void>>::value || is_constructible<fmt::v5::internal::fallback_formatter<INPUT_ENUM, char,
      void>>::value)' was not satisfied [with T = INPUT_ENUM]
  FMT_CONSTEXPR const T& map(const T& val) {
                         ^
./extlib/include/fmt/core.h:833:50: note: candidate template ignored: could not match 'named_arg<type-parameter-0-0, char>' against 'const INPUT_ENUM'
  FMT_CONSTEXPR const named_arg_base<char_type>& map(
                                                 ^
4 errors generated.
```

**Comment by vitaut** [comment]
What is `INPUT_ENUM`? The name suggests that it is some kind of an enum and it appears to be convertible to arithmetic types (ambiguously), but `std::is_enum<INPUT_ENUM>::value` is false, thus the error. Please provide a self-contained repro.

**Comment by SnapperTT** [comment]
Cheers for getting back to me

INPUT_ENUM is an enum and is castable (in my case) to an uint16. Its defined by https://github.com/aantron/better-enums, a clever lib that pairs enums to readable strings. 

I've fixed this on my end by either explicitly casting it to a uint16_t, or by calling theEnum._to_string()

I've been unable to isolate it - I've created a self contained repro and it compiles fine with both gcc and clang. It appears that this is a better-enums issue, so I'll close this
