### ISSUE TITLE
Compile Error with C++20 & Clang 20 (FMT_STRING macro issue)

### ISSUE THREAD

**Issue by ahoarau** [fmtlib/fmt#4247]
Hi,
I've having a compile error while testing the upcoming clang 20 with c++20 (and above).
It looks like https://github.com/fmtlib/fmt/issues/4218, but I could not manage to find a working patch.

```cpp
#include <fmt/format.h>
int main() { fmt::print("{}", 42); }
```

Compiler error:
```cmake
cmake_minimum_required(VERSION 3.24)
project(clang20-fmt)

set(CMAKE_CXX_STANDARD 20) # fmt will build with c++20
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include(FetchContent)
FetchContent_Declare(
  fmt
  URL https://github.com/fmtlib/fmt/releases/download/11.0.2/fmt-11.0.2.zip
)
FetchContent_MakeAvailable(fmt)

add_executable(example example.cc)
target_link_libraries(example PRIVATE fmt::fmt)
```

Here's a snippet of the output, seems to be an issue with the `FMT_STRING(s)` macro:
```
[build] /dev/clang20-fmt/build/Debug/_deps/fmt-src/src/os.cc:176:35: error: call to consteval function 'fmt::basic_format_string<char, const char *>::basic_format_string<FMT_COMPILE_STRING, 0>' is not a constant expression
[build]   176 |     FMT_THROW(system_error(errno, FMT_STRING("cannot open file {}"),
```

Complete output: 
[2-CMakeBuild.log](https://github.com/user-attachments/files/17958958/2-CMakeBuild.log)

The project (you need clang built from main branch !): 
[clang20-fmt.zip](https://github.com/user-attachments/files/17958884/clang20-fmt.zip)

**Comment by vitaut** [comment]
Looks like #4177 which has already been fixed. Does it work on master?

**Comment by ahoarau** [comment]
@vitaut Compiles on master, thanks ! a `11.0.3` coming up soon ?

**Comment by vitaut** [comment]
> a 11.0.3 coming up soon ?

Yes by some definition of soon.
