### ISSUE TITLE
fmtlib does not compile with MSVC v140

### ISSUE THREAD

**Issue by csandmann** [fmtlib/fmt#4346]
# Issue
The MSVC v140 build breaks with the attached errors.

```
format.cc
fmt\include\fmt\base.h(743): error C2327: 'fmt::v11::basic_specs::data_': is not a type name, static, or enumerator [fmt\build\fmt.vcxproj]
fmt\include\fmt\base.h(743): error C2065: 'data_': undeclared identifier [fmt\build\fmt.vcxproj]
fmt\include\fmt\base.h(743): error C2338:  [fmt\build\fmt.vcxproj]
```

# System
*Visual Studio 2022 (17.12.4)* with *MSVC v140 - VS 2015 C++-Buildtools (v14.00)*

# Details
- Latest visual studio toolchain (v1942) builds without issues

# Steps to reproduce
1. `git checkout v1.15.1`
2. `cmake -T v140 -S . -B build/ && cmake --build build/`

**Comment by sergiud** [comment]
Even if one fixes this issue there's still a ton of different seemingly unrelated compile errors starting with the 11.1.x release series. Bisecting leads to 761d35f7632a1dada0be8e6e9d18a3ba16644f00 as the first bad commit.

**Comment by vitaut** [comment]
This looks like a compile bug considering that `data_` is defined in https://github.com/fmtlib/fmt/blob/d42a068dbd4c6bcec8858ec642cf6a38503584a2/include/fmt/base.h#L742

and it works on other versions. I recommend updating to a newer compiler version, e.g. v141 which is known to work: https://github.com/fmtlib/fmt/actions/runs/13189537160/job/36820689152. If there is an easy workaround, a PR would be welcome too.

**Comment by edo9300** [comment]
A simple workaround could be to skip that static assert on msvc, since it will always be true

**Comment by vitaut** [comment]
I think it's fine to remove the static assert if it helps (a PR is welcome), it doesn't add much value anyway.

**Comment by sergiud** [comment]
No need to remove the `static_assert`. Qualifying the member is sufficient:
```patch
diff --git a/include/fmt/base.h b/include/fmt/base.h
index 8fdcea7c..ce71ad98 100644
--- a/include/fmt/base.h
+++ b/include/fmt/base.h
@@ -740,7 +740,7 @@ class basic_specs {
   };
 
   unsigned data_ = 1 << fill_size_shift;
-  static_assert(sizeof(data_) * CHAR_BIT >= 18, "");
+  static_assert(sizeof(basic_specs::data_) * CHAR_BIT >= 18, "");
 
   // Character (code unit) type is erased to prevent template bloat.
   char fill_data_[max_fill_size] = {' '};
```
As previously mentioned, however, this does not fix the compilation errors using the vc140 toolset because more errors arise after a fix.

**Comment by vitaut** [comment]
v140 is pretty old and we don't claim compatibility with it. But as I wrote earlier, if there is an easy fix, a PR would be welcome.
