### ISSUE TITLE
`to_string_view`  is not called when using fmt::join() with 6.0.0

### ISSUE THREAD

**Issue by AlexandreBossard** [fmtlib/fmt#1380]
Hi,
Here is a minimal code example:

```
#include <fmt/core.h>
#include <fmt/format.h>

#include <string>
#include <vector>

namespace my_ns {
// Tagged string
template <typename Tag> class StringWrapper : std::string {
  using base_t = std::string;
public:
  StringWrapper(base_t const &s) : base_t(s) {}
  base_t const &string() const noexcept { return *this; }
};

template <typename Tag>
fmt::string_view to_string_view(StringWrapper<Tag> const &s) {
  return s.string();
}
} // namespace my_ns

#if 1 // set to 0 to trigger compilation errors
namespace fmt {
template <typename Tag>
struct formatter<my_ns::StringWrapper<Tag>, char>
    : formatter<fmt::basic_string_view<char>, char> {
  template <typename FormatContext>
  auto format(my_ns::StringWrapper<Tag> const &str, FormatContext &ctx) {
    return formatter<fmt::basic_string_view<char>, char>::format(
        to_string_view(str), ctx);
  }
};
} // namespace fmt
#endif
struct Email {}; // A Tag

void test1() {
  auto const s = my_ns::StringWrapper<Email>{"bob@provider.com"};
  fmt::print("{}\n", s);
}
void test2() {
  std::vector<my_ns::StringWrapper<Email>> emails = {{"bob@provider.com"},
                                                     {"alice@provider.com"}};
  fmt::print("{}\n", fmt::join(emails, ", "));
}

int main(int ac, char **argv) {
  test1();
  test2();
  return 0;
}
```
the `to_string_view` works fine on a single value (test1), but is not called when using `fmt::join()` (test2). Thus, You need to have a custom type formatter, which does called the to_string_view here.

This was working fine with **fmt/5.3.0**, but it doesn't anymore with **fmt/6.0.0**.

**Comment by vitaut** [comment]
The old behavior was accidental. `to_string_view` is not an extension API and to make a type work with `join`, a `formatter` specialization should be provided.

**Comment by AlexandreBossard** [comment]
The documentation is not accurate or at least misleading then:
https://fmt.dev/latest/api.html#_CPPv2N3fmt14to_string_viewEPK4Char

This feature is not very useful if it's contrived to the format string only (probably loosing static check).

Accidental or not it was quite nice to have and easy to understand and implement.

**Comment by vitaut** [comment]
The difference is that `to_string_view` allows you to add support for custom format strings while `join` works with format arguments.

**Comment by vitaut** [comment]
> Accidental or not it was quite nice to have and easy to understand and implement.

I'm considering adding an API to address the use case of formatting objects of one type in terms of another. `to_string_view` is very limited and adding support for it to `join` is probably not worth the complexity.

**Comment by AlexandreBossard** [comment]
Getting back to it this morning in order to remove the `to_string_view` overload while keeping the `formatter`, I was meet with a load of errors. I needed both or it won't compiled. Sadly the `fmt::interna::is_string<>` was triggering an error instead of unselecting the overload because I am inheriting privately from std::string.

https://github.com/fmtlib/fmt/pull/1386 resolve this.
