### ISSUE TITLE
_format with named placeholders *and* format specifier does not work in clang/gcc

### ISSUE THREAD

**Issue by an-ky** [fmtlib/fmt#1002]
Hi 

I get a compiler error when using the `_format` UDL with a specific format string using fmtlib 5.2.1 and 5.3.0 using clang 7. The same string works with msvc 19.5.0.

Here is a minimal example to show the error. Do I something wrong here?

```
#include <fmt/format.h>

int main() {
    using namespace fmt::literals;
    "{number:0.2f}"_format("number"_a=1.23);
}
```

results in the following compiler errors (clang 7.0)

```
In file included from <source>:1:

/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:3439:29: error: constexpr variable 'invalid_format' must be initialized by a constant expression

    FMT_CONSTEXPR_DECL bool invalid_format =

                            ^

<source>:5:27: note: in instantiation of function template specialization 'fmt::v5::internal::udl_formatter<char, '{', 'n', 'u', 'm', 'b', 'e', 'r', ':', '0', '.', '2', 'f', '}'>::operator()<fmt::v5::internal::named_arg<double, char> >' requested here

    "{number:0.2f}"_format("number"_a=1.23);

                          ^

/opt/compiler-explorer/libs/fmt/trunk/include/fmt/core.h:919:19: note: non-constexpr function 'on_error' cannot be used in a constant expression

    ErrorHandler::on_error(message);

                  ^

/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:2089:14: note: in call to '&checker.context_->on_error(&"unknown format specifier"[0])'

    context_.on_error(message);

             ^

/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:2042:26: note: in call to '&checker->on_error(&"unknown format specifier"[0])'

          return handler.on_error("unknown format specifier");

                         ^

/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:2113:3: note: in call to 'parse_format_string({&s[0], 13}, checker)'

  parse_format_string<true>(s, checker);

  ^

/opt/compiler-explorer/libs/fmt/trunk/include/fmt/format.h:3440:9: note: in call to 'do_check_format_string({&s[0], 13}, {})'

        do_check_format_string<Char, error_handler, Args...>(

        ^

/opt/compiler-explorer/libs/fmt/trunk/include/fmt/core.h:327:16: note: declared here

  FMT_API void on_error(const char *message);

               ^

1 error generated.

Compiler returned: 1
```

The code compiles when the type specifier is removed from the format string. Furthermore using `fmt::format` even works *with* the type specifier, please see below.

```
#include <fmt/format.h>

int main() {
    using namespace fmt::literals;
    "{number}"_format("number"_a=1.23); // works
    fmt::format("{number:0.1f}", "number"_a=1.23); // works
}
```

For further reference please see https://godbolt.org/z/1-Knvq

Greets
An

**Comment by vitaut** [comment]
Thanks for reporting. Looks like the named argument is not unwrapped to get its underlying type somewhere.

**Comment by vitaut** [comment]
I looked into it in more details and the reason why it doesn't work at the moment is that compile-time format string checker doesn't handle named arguments. In fact, in the current standard it's not possible to implement this without awkward workarounds (e.g. constexpr lambda wrapped in a macro). It might be possible to do in C++20. Until then you can use the normal `format` function:

```c++
fmt::format("{number:0.1f}", "number"_a=1.23);
```
