### ISSUE TITLE
std::ostream support for fmt::printf is broken since f72a905

### ISSUE THREAD

**Issue by 375gnu** [fmtlib/fmt#1631]
Consider the following example:
```
#include <fmt/printf.h>
#include <filesystem>
int main()
{
        fmt::printf("%s\n", std::filesystem::path("/dev/null"));
}
```
Since f72a905 it's not possible to compile it:
```
include/fmt/format.h:2680:53: error: ‘class fmt::v6::basic_printf_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>’ has no member named ‘error_handler’
                                                 ctx.error_handler());
                                                 ~~~~^~~~~~~~~~~~~
include/fmt/format.h:2683:48: error: no matching function for call to ‘fmt::v6::basic_printf_context<std::back_insert_iterator<fmt::v6::internal::buffer<char> >, char>::arg(fmt::v6::basic_string_view<char>&)’
     value = internal::get_dynamic_spec<Handler>(ctx.arg(ref.val.name),
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
                                                 ctx.error_handler());
                                                 ~~~~~~~~~~~~~~~~~~~~
```
[Full g++ error.log](https://github.com/fmtlib/fmt/files/4466215/error.log)

I tested with gcc 7 & 8 and clang 9 but with gcc 7 lib.

**Comment by vitaut** [comment]
Fixed in https://github.com/fmtlib/fmt/commit/e99809f29da1002e8b9246e9278084ad231174e5. Thanks for reporting!
