### ISSUE TITLE
Watchman fails to build with fmt 8.1.0+

### ISSUE THREAD

**Issue by carlocab** [fmtlib/fmt#2717]
Hi there, we're trying to update Homebrew's version of [Watchman](https://github.com/facebook/watchman) at Homebrew/homebrew-core#92869. We were last able to build Watchman against fmt 8.0.1, and it now no longer builds since Homebrew's fmt was updated to 8.1.0. The build occurs on multiple versions of macOS and on Linux.

The Watchman build fails with [this error](https://github.com/Homebrew/homebrew-core/runs/4769183573?check_suite_focus=true#step:6:523):
```
  In file included from /tmp/watchman-20220110-77236-142y8ko/watchman-2022.01.10.00/watchman/PendingCollection.cpp:8:
  In file included from /tmp/watchman-20220110-77236-142y8ko/watchman-2022.01.10.00/watchman/PendingCollection.h:11:
  In file included from /opt/homebrew/include/folly/futures/Promise.h:23:
  In file included from /opt/homebrew/include/folly/futures/detail/Core.h:27:
  In file included from /opt/homebrew/include/folly/Executor.h:25:
  In file included from /opt/homebrew/include/folly/Range.h:45:
  In file included from /opt/homebrew/include/fmt/format.h:48:
  /opt/homebrew/include/fmt/core.h:1722:3: error: static_assert failed due to requirement 'formattable_pointer' "Formatting of non-void pointers is disallowed."
    static_assert(formattable_pointer,
    ^             ~~~~~~~~~~~~~~~~~~~
```

Complete build logs available at https://github.com/Homebrew/homebrew-core/actions/runs/1680135847.

I tried to follow the call stack (see the log after the snippet I pasted above), and it doesn't look to me that Watchman is passing any pointers at all to fmt. However, I don't really do C++, and I'm unfamiliar with Watchman's codebase, so I could be mistaken.

Any assistance trying to resolve this would be appreciated. Thank you!

**Comment by vitaut** [comment]
I'll look into it, thanks for reporting.

**Comment by vitaut** [comment]
The problem is that `w_string` is implicitly convertible to a pointer which is caught by a new diagnostic (compile-time error) introduced in {fmt} 8.1:

> Added missing diagnostic when trying to format function and member pointers as well as objects convertible to pointers which is explicitly disallowed

Fixed in https://github.com/fmtlib/fmt/commit/8f8a1a02d5c5cb967d240feee3ffac00d66f22a2 by only giving the diagnostic if there is not `formatter` specialization.

**Comment by carlocab** [comment]
Thanks for the lightning-quick fix. I've confirmed that it works.

**Comment by gh-andre** [comment]
@vitaut I just ran into the same bug. When this is planned to be released? If it's going to be some time, would you mind pointing out which commits can be used as a patch for 8.1.0 or 8.1.1 in the meantime? Thanks.

**Comment by carlocab** [comment]
https://github.com/fmtlib/fmt/commit/8f8a1a02d5c5cb967d240feee3ffac00d66f22a2 (mentioned above) applies cleanly to at least 8.1.1.

**Comment by gh-andre** [comment]
@carlocab Thanks. There's a lot of commits around I was hoping to hear from the maintainers what would work well for a patch until the next release. It would be nice if an 8.1 branch was maintained for these patch fixes.

**Comment by vitaut** [comment]
https://github.com/fmtlib/fmt/commit/8f8a1a02d5c5cb967d240feee3ffac00d66f22a2 is pretty self-contained. It will also be included in the next release but I don't have any specific dates yet.

**Comment by gh-andre** [comment]
@vitaut Sounds good. Thanks for confirming.
