### ISSUE TITLE
a strange problem

### ISSUE THREAD

**Issue by dubhokku** [fmtlib/fmt#4106]
Hello, i have somehow fmt has conflicts with something

```
[ 45%] Building CXX object src/core/CMakeFiles/project.dir/Controller.cc.o
In file included from /home/user/.conan2/p/b/spdloabe47375597b3/p/include/spdlog/fmt/fmt.h:28,
                 from /home/user/.conan2/p/b/spdloabe47375597b3/p/include/spdlog/common.h:50,
                 from /home/user/.conan2/p/b/spdloabe47375597b3/p/include/spdlog/spdlog.h:12,
                 from /home/user/.conan2/p/b/project99e7771cf5b02/b/include/project/core/logging.hpp:26,
                 from /home/user/.conan2/p/b/project99e7771cf5b02/b/src/core/project_autogen/EWIEGA46WW/../../Controller.hpp:24,
                 from /home/user/.conan2/p/b/project99e7771cf5b02/b/src/core/project_autogen/EWIEGA46WW/moc_Controller.cpp:10,
                 from /home/user/.conan2/p/b/project99e7771cf5b02/b/src/core/project_autogen/mocs_compilation.cpp:2:
/home/user/.conan2/p/b/fmtb73436f8e1397/p/include/fmt/core.h:1581:68: error: template argument 1 is invalid
 1581 | template <bool PACKED, typename Context, typename T, FMT_ENABLE_IF(PACKED)>
      |                                                                    ^~~~~~
/home/user/.conan2/p/b/fmtb73436f8e1397/p/include/fmt/core.h:1581:54: error: expected ‘>’ before ‘)’ token
 1581 | template <bool PACKED, typename Context, typename T, FMT_ENABLE_IF(PACKED)>
      |                                                      ^~~~~~~~~~~~~
/home/user/.conan2/p/b/fmtb73436f8e1397/p/include/fmt/core.h:1581:54: error: expected unqualified-id before ‘)’ token
/home/user/.conan2/p/b/fmtb73436f8e1397/p/include/fmt/core.h:1618:69: error: template argument 1 is invalid
 1618 | template <bool PACKED, typename Context, typename T, FMT_ENABLE_IF(!PACKED)>
      |                                                                     ^~~~~~
/home/user/.conan2/p/b/fmtb73436f8e1397/p/include/fmt/core.h:1618:54: error: expected ‘>’ before ‘)’ token
 1618 | template <bool PACKED, typename Context, typename T, FMT_ENABLE_IF(!PACKED)>
      |                                                      ^~~~~~~~~~~~~
/home/user/.conan2/p/b/fmtb73436f8e1397/p/include/fmt/core.h:1618:54: error: expected unqualified-id before ‘)’ token
```

related issue  https://github.com/fmtlib/fmt/issues/4063

I tried to build with gcc-9.5, gcc-11.4 and gcc-13.2 with the same result.
What should I do to fix it?

**Comment by dubhokku** [comment]
but i have't  amx.h

```
/mnt/z/My Projects/Zutils/libs/legacy-sdk/amx/amx.h:269:47: error: template argument 1 is invalid
  269 |   #define PACKED        __attribute__((packed))
```

**Comment by vitaut** [comment]
By "same" I meant that it also looks like a macro conflict. If this is not the case please provide a self-contained repro, ideally on godbolt.
