### ISSUE TITLE
Undefined symbols: gmtime_s and localtime_s

### ISSUE THREAD

**Issue by gsjaardema** [fmtlib/fmt#1754]
Using the intel-17 compiler, I get a compilation error that `gmtime_s` and `localtime_s` are undefined symbols in `chrono.h`.  Googling, I found a page that indicates that support for these functions is "optional" and they are only provided if `__STDC_LIB_EXT1__` is defined and then to use them, you must define `__STDC_WANT_LIB_EXT1__` to 1.  Obviously this is compiler dependent since gcc and clang seem to compile this include file with no problems.

I am also able to compile this with intel-19.0 without the define, and if I do the recommended check below, it fails with the "Not defined" error on both systems.

I'm not sure if there is a better way to check whether `gmtime_s` and `localtime_s` are defined and skip using them if they aren't defined.  I know that intel-17.0 is an older compiler and newer versions compile correctly, but we have a few people who are stuck on that version for some reason... 

This is happening with the last three releases of fmtlib.

```
#if defined(__STDC_LIB_EXT1__)
  #if (__STDC_LIB_EXT1__ >= 201112L)
    #define USE_EXT1 1
    #define __STDC_WANT_LIB_EXT1__ 1 /* Want the ext1 functions */
  #endif
  #error "Not defined"
#endif
```

**Comment by vitaut** [comment]
The fallback `gmtime_s` is defined here: https://github.com/fmtlib/fmt/blob/f19b1a521ee8b606dedcadfda69fd10ddf882753/include/fmt/chrono.h#L314

Could you post the full error?

**Comment by gsjaardema** [comment]
Here is the error we are getting:
```
In file included from /projects/ccsm/AlbanyTrilinos_20200702/trilinos/trilinos-src/packages/seacas/libraries/ioss/src/Ioss_Utils.C(21):
/projects/ccsm/AlbanyTrilinos_20200702/trilinos/trilinos-src/packages/seacas/libraries/ioss/src/fmt/chrono.h(62): error: identifier "localtime_s" is undefined
        return fallback(localtime_s(&tm_, &time_));
                        ^

In file included from /projects/ccsm/AlbanyTrilinos_20200702/trilinos/trilinos-src/packages/seacas/libraries/ioss/src/Ioss_Utils.C(21):
/projects/ccsm/AlbanyTrilinos_20200702/trilinos/trilinos-src/packages/seacas/libraries/ioss/src/fmt/chrono.h(106): error: identifier "gmtime_s" is undefined
        return fallback(gmtime_s(&tm_, &time_));
```

**Comment by vitaut** [comment]
What {fmt} version are you using?

**Comment by gsjaardema** [comment]
The original failure reported was with 6.0.0, but I also reproduced with 6.2.0 and 7.0.0

**Comment by vitaut** [comment]
Might be worth investigating why the compiler doesn't find the function which is clearly defined above but unfortunately I don't have an Intel compiler at hand.

**Comment by vitaut** [comment]
Seems to work fine on godbolt: https://godbolt.org/z/Qa7Xfy

**Comment by gsjaardema** [comment]
Interesting.  I will try to shorten my failing file and see if I can determine what is causing the issue.  Thanks for looking into this.

**Comment by gsjaardema** [comment]
I can reproduce this on `intel-17.0.2 20170213` but it works correctly on `intel-17.0.1 20161005` on a different system. 

On the failing system, `17.0.2.174` fails, `17.0.1.132` works, `17.0.4.196` works.  

Looks like this is probably a very specific issue related to one very specific compiler version on one system...  Not worth trying to fix this since I don't think it is a problem with fmtlib, but a problem with our compiler installation.

Thanks for looking into this.
