### ISSUE TITLE
i686 build issue with version 12.2.0 : include/fmt/format.h:3108:14: error: no match for ‘operator~’ (operand type is ‘fmt::v12::detail::uint128’)

### ISSUE THREAD

**Issue by satmandu** [fmtlib/fmt#4886]
We're seeing this build issue only with our i686 build with GCC 16.2 built against Glibc 2.23. We have no problems with x86_64 or armv7l builds built against glibc 2.27.

```
cmake_options: -DBUILD_SHARED_LIBS=TRUE -DFMT_TEST=OFF
The no-dev option is deprecated.  Use -Wno-author instead.
-- CMake version: 4.4.2-dirty
-- The CXX compiler identification is GNU 16.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- {fmt} version: 12.2.0
-- Build type: Release
-- Target 'doc' disabled because mkdocs not found
-- Configuring done (0.5s)
CMake Warning (unused-cli):
  Manually-specified variables were not used by the project:
    CMAKE_C_FLAGS
    CMAKE_LIBRARY_PATH
-- Generating done (0.0s)
-- Build files have been written to: /usr/local/tmp/crew/libfmt.20260813161304.dir/builddir
ninja: Entering directory `./builddir'
ninja: Jobserver mode detected:  -j4 --jobserver-auth=fifo:/usr/local/tmp/crew/libfmt.20260813161304.dir/jobserver_pool
[1/6] Building CXX object CMakeFiles/fmt-c.dir/src/fmt-c.cc.o
[2/6] Building CXX object CMakeFiles/fmt.dir/src/os.cc.o
[3/6] Building CXX object CMakeFiles/fmt.dir/src/format.cc.o
FAILED: [code=1] CMakeFiles/fmt.dir/src/format.cc.o 
/usr/local/bin/c++ -DFMT_LIB_EXPORT -Dfmt_EXPORTS -I/usr/local/tmp/crew/libfmt.20260813161304.dir/include -O3 -pipe -ffat-lto-objects -fPIC  -flto=auto -flto=auto -O3 -DNDEBUG -flto=auto -fno-fat-lto-objects -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -MD -MT CMakeFiles/fmt.dir/src/format.cc.o -MF CMakeFiles/fmt.dir/src/format.cc.o.d -o CMakeFiles/fmt.dir/src/format.cc.o -c /usr/local/tmp/crew/libfmt.20260813161304.dir/src/format.cc
In file included from /usr/local/tmp/crew/libfmt.20260813161304.dir/include/fmt/format-inl.h:28,
                 from /usr/local/tmp/crew/libfmt.20260813161304.dir/src/format.cc:8:
/usr/local/tmp/crew/libfmt.20260813161304.dir/include/fmt/format.h: In instantiation of ‘constexpr void fmt::v12::detail::format_hexfloat(Float, fmt::v12::format_specs, buffer<char>&) [with Float = long double; typename std::enable_if<(! std::integral_constant<bool, (std::numeric_limits<_Tp>::digits == 106)>::value), int>::type <anonymous> = 0]’:
/usr/local/tmp/crew/libfmt.20260813161304.dir/include/fmt/format.h:3501:20:   required from ‘constexpr OutputIt fmt::v12::detail::write(OutputIt, T, fmt::v12::format_specs, fmt::v12::locale_ref) [with Char = char; OutputIt = fmt::v12::basic_appender<char>; T = long double; typename std::enable_if<is_floating_point<T>::value, int>::type <anonymous> = 0]’
 3501 |     format_hexfloat(convert_float(value), specs, buffer);
      |     ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/tmp/crew/libfmt.20260813161304.dir/include/fmt/format.h:3595:21:   required from ‘OutputIt fmt::v12::detail::write(OutputIt, T) [with Char = char; OutputIt = fmt::v12::basic_appender<char>; T = long double; typename std::enable_if<(is_floating_point<T>::value && (! is_fast_float<T>::value)), int>::type <anonymous> = 0]’
 3595 |   return write<Char>(out, value, {});
      |          ~~~~~~~~~~~^~~~~~~~~~~~~~~~
/usr/local/tmp/crew/libfmt.20260813161304.dir/include/fmt/format.h:3685:16:   required from ‘void fmt::v12::detail::default_arg_formatter<Char>::operator()(T) [with T = long double; typename std::enable_if<std::integral_constant<bool, (std::is_same<T, int>::value || 1)>::value, int>::type <anonymous> = 0; Char = char]’
 3685 |     write<Char>(out, value);
      |     ~~~~~~~~~~~^~~~~~~~~~~~
/usr/local/tmp/crew/libfmt.20260813161304.dir/include/fmt/base.h:2505:52:   required from ‘constexpr decltype (vis(0)) fmt::v12::basic_format_arg<Context>::visit(Visitor&&) const [with Visitor = fmt::v12::detail::default_arg_formatter<char>; Context = fmt::v12::context; decltype (vis(0)) = void]’
 2505 |     case detail::type::long_double_type: return vis(value_.long_double_value);
      |                                                 ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/tmp/crew/libfmt.20260813161304.dir/include/fmt/format-inl.h:1471:29:   required from here
 1471 |     return args.get(0).visit(default_arg_formatter<char>{out});
      |            ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/tmp/crew/libfmt.20260813161304.dir/include/fmt/format.h:3108:14: error: no match for ‘operator~’ (operand type is ‘fmt::v12::detail::uint128’)
 3108 |       f.f &= ~(inc - 1);
      |              ^~~~~~~~~~
ninja: build stopped: subcommand failed.

```

**Comment by vitaut** [comment]
Same as #4811
