### ISSUE TITLE
Wide format string not working

### ISSUE THREAD

**Issue by davidaue** [fmtlib/fmt#2387]
fmtlib 8.0.0 compiling with the latest MSVC 2019:

    #include <fmt/format.h>
    
    void foo()
    {
        fmt::format(L"Bar");
    }

    error C2664: 'std::string fmt::v7::format<>(fmt::v7::basic_format_string<char>)': cannot convert argument 1 from 'const wchar_t [4]' to 'fmt::v7::basic_format_string<char>'

This works in 7.1.3. It looks like 8.0.0 no longer has the char type for the format string templated and only returns std::string.

**Comment by mwinterb** [comment]
You need to include `<fmt/xchar.h>`.

**Comment by davidaue** [comment]
@mwinterb Thanks!!

https://fmt.dev/latest/api.html needs an update.

> fmt/format.h: the full format API providing compile-time format string checks, **wide string**, output iterator and user-defined type support

**Comment by davidaue** [comment]
@mwinterb

I see the 8.0.0 docs are already updated in the repo. There is a reference to "wchar_t.h" that appears it should be "xchar.h". (https://github.com/fmtlib/fmt/blob/master/doc/api.rst#wchar_t-support)

The live page at fmt.dev doesn't have 8.0.0 docs up yet.

**Comment by vitaut** [comment]
The docs will be updated soon and in the meantime you can use https://fmt.dev/dev/.
