### ISSUE TITLE
fmt::format and custom string-type not working in v8.0.0

### ISSUE THREAD

**Issue by std-any-emplace** [fmtlib/fmt#2405]
This used to work under v7.1.3

```
struct OwnString
{
	char buffer[16];
};

inline fmt::string_view to_string_view(const OwnString& a_string)
{
	return {a_string.buffer, strlen(a_string.buffer)};
}

TEST_CASE("fmt.ownstring - OwnString als FormatString")
{
	const auto str = OwnString{"abc {}\0"};
	CHECK(fmt::format(str, 123) == "abc 123");
}
```
Now this fails with 
```
error: no matching function for call to ?format(const OwnString&, int)?
  194 |  CHECK(fmt::format(str, 123) == "abc 123");
```
for gcc 10.3.0 / c++17

**Comment by vitaut** [comment]
This is no longer support because the format string must be known at compile time for compile-time checks to work. You can provide your own `format` function that takes `OwnString` instead.

**Comment by std-any-emplace** [comment]
It it still documented as a supported feature: https://fmt.dev/latest/api.html#_CPPv4I0_iEN3fmt14to_string_viewE17basic_string_viewI4CharEPK4Char

**Comment by vitaut** [comment]
`to_string_view` is still available but not for format strings (it was actually never recommended as such but happened to work).

**Comment by vitaut** [comment]
The example is incorrect though.
