### ISSUE TITLE
Build error with 10.1.0:  error: no matching function for call to ‘make_arg<fmt::v10::format_context>(int)’     8 |     fmt::detail::make_arg<fmt::format_context>(42);

### ISSUE THREAD

**Issue by hdejin** [fmtlib/fmt#3596]
The following no longer builds with 10.1.0. This is breaking MariaDB (10.11.4) builds:
```
#define FMT_STATIC_THOUSANDS_SEPARATOR ','
#define FMT_HEADER_ONLY 1
#include <fmt/format-inl.h>
#include <iostream>

int main() {
  fmt::format_args::format_arg arg=
    fmt::detail::make_arg<fmt::format_context>(42);
  std::cout << fmt::vformat("The answer is {}.",
    fmt::format_args(&arg, 1));
}

```

Getting the following error:
```
s.cpp: In function ‘int main()’:
s.cpp:8:47: error: no matching function for call to ‘make_arg<fmt::v10::format_context>(int)’
    8 |     fmt::detail::make_arg<fmt::format_context>(42);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
In file included from /usr/include/fmt/format.h:49,
                 from /usr/include/fmt/format-inl.h:25,
                 from s.cpp:3:
/usr/include/fmt/core.h:1588:20: note: candidate: ‘constexpr fmt::v10::basic_format_arg<Context> fmt::v10::detail::make_arg(T&) [with Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = int]’ (near match)
 1588 | FMT_CONSTEXPR auto make_arg(T& val) -> basic_format_arg<Context> {
      |                    ^~~~~~~~
/usr/include/fmt/core.h:1588:20: note:   conversion of argument 1 would be ill-formed:
s.cpp:8:48: error: cannot bind non-const lvalue reference of type ‘int&’ to an rvalue of type ‘int’
    8 |     fmt::detail::make_arg<fmt::format_context>(42);
      |                                                ^~
/usr/include/fmt/core.h:1559:31: note: candidate: ‘template<bool PACKED, class Context, class T, typename std::enable_if<PACKED, int>::type <anonymous> > constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&)’
 1559 | FMT_CONSTEXPR FMT_INLINE auto make_arg(T& val) -> value<Context> {
      |                               ^~~~~~~~
/usr/include/fmt/core.h:1559:31: note:   template argument deduction/substitution failed:
s.cpp:8:47: error: type/value mismatch at argument 1 in template parameter list for ‘template<bool PACKED, class Context, class T, typename std::enable_if<PACKED, int>::type <anonymous> > constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&)’
    8 |     fmt::detail::make_arg<fmt::format_context>(42);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
s.cpp:8:47: note:   expected a constant of type ‘bool’, got ‘fmt::v10::format_context’ {aka ‘fmt::v10::basic_format_context<fmt::v10::appender, char>’}
/usr/include/fmt/core.h:1596:27: note: candidate: ‘template<bool PACKED, class Context, class T, typename std::enable_if<(! PACKED), int>::type <anonymous> > constexpr fmt::v10::basic_format_arg<Context> fmt::v10::detail::make_arg(T&)’
 1596 | FMT_CONSTEXPR inline auto make_arg(T& val) -> basic_format_arg<Context> {
      |                           ^~~~~~~~
/usr/include/fmt/core.h:1596:27: note:   template argument deduction/substitution failed:
s.cpp:8:47: error: type/value mismatch at argument 1 in template parameter list for ‘template<bool PACKED, class Context, class T, typename std::enable_if<(! PACKED), int>::type <anonymous> > constexpr fmt::v10::basic_format_arg<Context> fmt::v10::detail::make_arg(T&)’
    8 |     fmt::detail::make_arg<fmt::format_context>(42);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
s.cpp:8:47: note:   expected a constant of type ‘bool’, got ‘fmt::v10::format_context’ {aka ‘fmt::v10::basic_format_context<fmt::v10::appender, char>’}
```
