### ISSUE TITLE
error: declaration of ‘__locale_struct* newlocale(int, const char*, LocaleType)’ has a different exception specifier

### ISSUE THREAD

**Issue by vedranmiletic** [fmtlib/fmt#1272]
Fails to build on Debian with GCC 5.5 with `-DFMT_PEDANTIC=ON`. Compilation fails with the following error:

```
[54/55] Building CXX object test/CMakeFiles/posix-mock-test.dir/posix-mock-test.cc.o
FAILED: test/CMakeFiles/posix-mock-test.dir/posix-mock-test.cc.o
/usr/bin/ccache  g++-5  -DFMT_LOCALE -DFMT_USE_FILE_DESCRIPTORS=1 -DGTEST_HAS_STD_WSTRING=1 -D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING=1 -Iinclude -isystem test/gtest -isystem test/gmock -isystem test/. -O3 -DNDEBUG   -pedantic-errors -Wall -Wextra -pedantic -Wold-style-cast -Wundef -Wredundant-decls -Wwrite-strings -Wpointer-arith-Wcast-qual -Wformat=2 -Wmissing-include-dirs -Wcast-align -Wnon-virtual-dtor -Wctor-dtor-privacy -Wdisabled-optimization -Winvalid-pch -Woverloaded-virtual -Wconversion -Wno-ctor-dtor-privacy -Wno-format-nonliteral -Wno-shadow -Wnoexcept -Wno-dangling-else -Wno-unused-local-typedefs -Wdouble-promotion -Wtrampolines -Wzero-as-null-pointer-constant -Wuseless-cast -Wvector-operation-performance -Wsized-deallocation -std=gnu++11 -MD -MT test/CMakeFiles/posix-mock-test.dir/posix-mock-test.cc.o -MF test/CMakeFiles/posix-mock-test.dir/posix-mock-test.cc.o.d -o test/CMakeFiles/posix-mock-test.dir/posix-mock-test.cc.o -c test/posix-mock-test.cc
test/posix-mock-test.cc: In function ‘__locale_struct* newlocale(int, const char*, LocaleType)’:
test/posix-mock-test.cc:493:37: error: declaration of ‘__locale_struct* newlocale(int, const char*, LocaleType)’ has a different exception specifier
                      LocaleType base) FMT_LOCALE_THROW {
                                     ^
In file included from include/fmt/posix.h:18:0,
                 from test/../src/posix.cc:13,
                 from test/posix-mock-test.cc:14:
/usr/include/locale.h:151:19: error: from previous declaration ‘__locale_struct* newlocale(int, const char*, __locale_t) throw ()’
 extern __locale_t newlocale (int __category_mask, const char *__locale,
                   ^
test/posix-mock-test.cc: In function ‘FreeLocaleResult freelocale(LocaleType)’:
test/posix-mock-test.cc:504:46: error: declaration of ‘FreeLocaleResult freelocale(LocaleType)’ has a different exception specifier
 FreeLocaleResult freelocale(LocaleType locale) FMT_LOCALE_THROW {
                                              ^
In file included from include/fmt/posix.h:18:0,
                 from test/../src/posix.cc:13,
                 from test/posix-mock-test.cc:14:
/usr/include/locale.h:190:13: error: from previous declaration ‘void freelocale(__locale_t) throw ()’
 extern void freelocale (__locale_t __dataset) __THROW;
             ^
test/posix-mock-test.cc: In function ‘double strtod_l(const char*, char**, LocaleType)’:
test/posix-mock-test.cc:510:34: error: declaration of ‘double strtod_l(const char*, char**, LocaleType)’ has a different exception specifier
                 LocaleType locale) FMT_LOCALE_THROW {
                                  ^
In file included from include/fmt/posix.h:20:0,
                 from test/../src/posix.cc:13,
                 from test/posix-mock-test.cc:14:
/usr/include/stdlib.h:221:15: error: from previous declaration ‘double strtod_l(const char*, char**, __locale_t) throw ()’
 extern double strtod_l (const char *__restrict __nptr,
               ^
```
