### ISSUE TITLE
spdlog (which uses fmt) doesn't work with nvcc 12.6 and c++20 (fmt bug?)

### ISSUE THREAD

**Issue by garko1** [fmtlib/fmt#4446]
Install nvcc 12.6 (or 12.9) and latest spdlog with `apt install libspdlog-dev` on e.g. Ubuntu. spdlog uses fmt. Minimum reproducible example is:

```
#include <spdlog/spdlog.h>

int main(int argc, char **argv) {
    return 0;
}
```
stored in e.g. `spdlog-error.cu`. Compile this with `nvcc -std=c++20 -c spdlog-error.cu` and it yields this error

```
/usr/include/fmt/core.h: In function ‘constexpr bool fmt::v8::detail::is_constant_evaluated(bool)’:
/usr/include/fmt/core.h:357:14: error: call to non-‘constexpr’ function ‘void fmt::v8::detail::ignore_unused(const T& ...) [with T = {bool}]’
  357 |   ignore_unused(default_value);
      |   ~~~~~~~~~~~^~~~~~~~~~~~~~~
/usr/include/fmt/core.h:352:28: note: ‘void fmt::v8::detail::ignore_unused(const T& ...) [with T = {bool}]’ declared here
  352 | template <typename... T> FMT_CONSTEXPR void ignore_unused(const T&...) {}
      |                            ^~~~~~~~~~~~~
/usr/include/fmt/format.h: In function ‘constexpr int fmt::v8::detail::count_digits(uint64_t)’:
/usr/include/fmt/format.h:985:29: error: call to non-‘constexpr’ function ‘int fmt::v8::detail::count_digits_fallback(T) [with T = long unsigned int]’
  985 |   return count_digits_fallback(n);
      |        ~~~~~~~~~~~~~~~~~~~~~^~~
/usr/include/fmt/format.h:936:25: note: ‘int fmt::v8::detail::count_digits_fallback(T) [with T = long unsigned int]’ declared here
  936 | template <typename T> FMT_CONSTEXPR auto count_digits_fallback(T n) -> int {
      |                         ^~~~~~~~~~~~~~~~~~~~~
/usr/include/fmt/format.h: In function ‘constexpr int fmt::v8::detail::count_digits(uint32_t)’:
/usr/include/fmt/format.h:1039:29: error: call to non-‘constexpr’ function ‘int fmt::v8::detail::count_digits_fallback(T) [with T = unsigned int]’
 1039 |   return count_digits_fallback(n);
      |        ~~~~~~~~~~~~~~~~~~~~~^~~
/usr/include/fmt/format.h:936:25: note: ‘int fmt::v8::detail::count_digits_fallback(T) [with T = unsigned int]’ declared here
  936 | template <typename T> FMT_CONSTEXPR auto count_digits_fallback(T n) -> int {
      | 
```

These are all latest versions in standard public Ubuntu .deb repo. Please check if this is an issue in fmt. I reported this to Nvidia and they said issue was not in nvcc:

```
After investigating , we think this is not a bug in nvcc , but from fmt and spdlog . It seems "fmt/core.h" has special handling for nvcc .
98 // Check if relaxed C++14 constexpr is supported. 99 // GCC doesn't allow throw in constexpr until version 6 (bug 67371). 100 #ifndef FMT_USE_CONSTEXPR 101 # define FMT_USE_CONSTEXPR \ 102 (FMT_HAS_FEATURE(cxx_relaxed_constexpr) || FMT_MSC_VER >= 1912 || \ 103 (FMT_GCC_VERSION >= 600 && __cplusplus >= 201402L)) && \ 104 !FMT_NVCC && !FMT_ICC_VERSION 105 #endif 106 #if FMT_USE_CONSTEXPR 107 # define FMT_CONSTEXPR constexpr 108 # define FMT_CONSTEXPR_DECL constexpr 109 #else 110 # define FMT_CONSTEXPR 111 # define FMT_CONSTEXPR_DECL 112 #endif
If you try fmt mainline https://github.com/fmtlib/fmt and https://github.com/gabime/spdlog.git mainline , they can compile well in nvcc 12.6 and latest 12.9 .
(base) local-yni@ipp1-0008:~/yni/5271815$ /usr/local/cuda-12.9/bin
vcc -ccbin=g++-14 -std=c++20 -x cu test.c -c nvcc warning : Support for offline compilation for architectures prior to '_75' will be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning). (base) local-yni@ipp1-0008:~/yni/5271815$ (base) local-yni@ipp1-0008:~/yni/5271815$ /usr/local/cuda-12.6/bin
vcc -ccbin=g++-11 -std=c++20 -x cu test.c -c (base) local-yni@ipp1-0008:~/yni/5271815$ (base) local-yni@ipp1-0008:~/yni/5271815$ cat test.c #include int main(int argc, char **argv) { return 0; } (base) local-yni@ipp1-0008:~/yni/5271815$
```

**Comment by sunmy2019** [comment]
The mainline has gone to v11, and the source you are using is v8. fmt won't patch on v8.

libspdlog-dev of Ubuntu is outdated. You can verify if the issue persists on latest version.

**Comment by vitaut** [comment]
`ignore_unused` is constexpr in the current master: https://github.com/fmtlib/fmt/blob/b5266fd3b91accec15d56a8f144b31dceed40d31/include/fmt/base.h#L363
