### ISSUE TITLE
Error lnk2001 unresolved external symbol after upgrade from 8.1.1 to 10.0.0 on Window 10 VS 2019

### ISSUE THREAD

**Issue by sfzhang** [fmtlib/fmt#3828]
Hi,
I encountered a link issue after upgraded fmt from 8.1.1 to 10.0.0 on Window 10 Visual Studio 2019.
`Transmission.obj:-1: error: LNK2001: Unresolved external symbol "public: __cdecl fmt::v10::detail::value<class fmt::v10::basic_format_context<class fmt::v10::appender,char> >::value<class fmt::v10::basic_format_context<class fmt::v10::appender,char> >(struct fmt::v10::detail::unformattable)" (??0?$value@V?$basic_format_context@Vappender@v10@fmt@@D@v10@fmt@@@detail@v10@fmt@@QEAA@Uunformattable@123@@Z)`

So could you please tell me what caused this issue?
Thanks!

**Comment by vitaut** [comment]
This overload is only used during format string validation and shouldn't normally appear in the binary. Please provide a repro, ideally on godbolt.

**Comment by vitaut** [comment]
Closing for now as it is not actionable without a repro but feel free to reopen when you provide one.

**Comment by dd123-a** [comment]
Has this issue been resolved yet?
